import "server-only";
import { createHash } from "node:crypto";
import { z } from "zod";
import type { CadastralContactPrefill, CadastralContext, CadastralHolder, CadastralOperationResult, CadastralOperationType, CadastralPropertyUnit } from "@/domain/cadastral-data";
import { createClient, hasSupabaseEnvironment } from "@/lib/supabase/server";
import { CadastralProviderError, OpenApiCatastoProvider, type CadastralDataProvider, type ProviderRequestState } from "./cadastral-data-provider";
import { paidCadastralServicePrice, type PaidServiceGovernance, type PaidServiceHistoryItem, type PaidServiceOperatorSummary } from "@/domain/paid-cadastral-services";

const contextSchema=z.object({recordId:z.string().uuid().optional(),provinceCode:z.string().trim().min(1).max(8),municipality:z.string().trim().min(1).max(160),municipalityCode:z.string().trim().min(1).max(8),section:z.string().trim().max(40).optional(),sheet:z.string().trim().min(1).max(40),parcel:z.string().trim().min(1).max(80)});
const record=z.record(z.string(),z.unknown());
type Db=Awaited<ReturnType<typeof createClient>>;

function text(value:unknown){return typeof value==="string"&&value?value:undefined}
function canonical(value:Record<string,unknown>){return JSON.stringify(Object.fromEntries(Object.entries(value).filter(([,item])=>item!==undefined&&item!=="").sort(([a],[b])=>a.localeCompare(b))))}
function requestHash(value:Record<string,unknown>){return createHash("sha256").update(canonical(value)).digest("hex")}
function providerMessage(error:unknown){return error instanceof CadastralProviderError?{code:error.code,message:error.message}:{code:"UPSTREAM_UNAVAILABLE",message:"Operazione catastale non completata."}}
function cadastralDataProvider():CadastralDataProvider{const token=process.env.OPENAPI_CATASTO_TOKEN;if(!token)throw new CadastralProviderError("NOT_CONFIGURED","Token OpenAPI Catasto non configurato.",false);const environment=process.env.OPENAPI_CATASTO_ENV??"sandbox";if(environment!=="sandbox"&&environment!=="production")throw new CadastralProviderError("NOT_CONFIGURED","Ambiente OpenAPI Catasto non valido.",false);return new OpenApiCatastoProvider(token,environment==="production"?"https://catasto.openapi.it":"https://test.catasto.openapi.it")}

async function authorize(db:Db){const {data:{user},error:userError}=await db.auth.getUser();if(userError||!user)throw new Error("Autenticazione richiesta.");const {data,error}=await db.rpc("can_use_paid_cadastral_services_lab");if(error||data!==true)throw new Error("Non sei autorizzato a utilizzare i servizi catastali a pagamento.");return user.id}

async function contextForRecord(db:Db,recordId:string):Promise<CadastralContext>{
  const {data,error}=await db.from("census_records").select("id,sheet,parcel,cadastral_associations(municipality_cadastral_code,municipality_name,section,sheet,parcel),census_zones(municipalities(name,cadastral_code,provinces(code)))").eq("id",recordId).single();
  if(error)throw new Error(error.message);const row=record.parse(data);const association=record.parse(Array.isArray(row.cadastral_associations)?row.cadastral_associations[0]:row.cadastral_associations??{});const zone=record.parse(row.census_zones);const municipality=record.parse(zone.municipalities);const province=record.parse(municipality.provinces);
  const parsed=contextSchema.safeParse({recordId,provinceCode:province.code,municipality:municipality.name,municipalityCode:association.municipality_cadastral_code??municipality.cadastral_code,section:association.section,sheet:association.sheet??row.sheet,parcel:association.parcel??row.parcel});if(!parsed.success)throw new Error("Dati catastali incompleti: servono provincia, comune, foglio e particella.");return parsed.data;
}

async function saveCompletedData(db:Db,requestId:string,recordId:string|undefined,context:CadastralContext,state:ProviderRequestState,selectedUnit?:CadastralPropertyUnit){
  const units=state.units.length?state.units:selectedUnit?[selectedUnit]:[];const storedUnits:Array<CadastralPropertyUnit&{id:string}>=[];
  for(const unit of units){const payload={census_record_id:recordId??null,source_request_id:requestId,provider:"OPENAPI_CATASTO",provider_property_id:unit.providerPropertyId,municipality_cadastral_code:context.municipalityCode,municipality_name:context.municipality,province_code:context.provinceCode,section:unit.section??context.section??null,urban_section:unit.urbanSection??null,sheet:unit.sheet,parcel:unit.parcel,subaltern:unit.subaltern??null,address:unit.address??null,census_zone:unit.censusZone??null,category:unit.category??null,class:unit.class??null,consistency:unit.consistency??null,cadastral_income:unit.cadastralIncome??null,registry_lot:unit.registryLot??null,acquired_at:new Date().toISOString(),raw_payload:state.raw};const {data,error}=await db.from("cadastral_property_units").upsert(payload,{onConflict:"provider,provider_property_id,source_request_id"}).select("id").single();if(error)throw new Error(error.message);storedUnits.push({...unit,id:String(record.parse(data).id)})}
  const ownerUnit=storedUnits.find(unit=>unit.providerPropertyId===selectedUnit?.providerPropertyId)??storedUnits[0];
  if(ownerUnit&&state.holders.length){for(const holder of state.holders){let possibleSubjectId:string|undefined;if(holder.taxCode){const normalized=holder.taxCode.replace(/[^a-zA-Z0-9]/g,"").toUpperCase();const {data}=await db.from("subjects").select("id").eq("tax_code",normalized).limit(1);const first=Array.isArray(data)?data[0]:undefined;if(first)possibleSubjectId=String(record.parse(first).id)}const {error}=await db.from("cadastral_ownership_rights").upsert({property_unit_id:ownerUnit.id,source_request_id:requestId,holder_type:holder.holderType,first_name:holder.firstName??null,last_name:holder.lastName??null,company_name:holder.companyName??null,tax_code:holder.taxCode??null,right_type_original:holder.rightTypeOriginal??null,share_original:holder.shareOriginal??null,source:"OPENAPI_CATASTO",raw_payload:state.raw},{ignoreDuplicates:true});if(error)throw new Error(error.message);holder.possibleSubjectId=possibleSubjectId}}
}

async function toResult(db:Db,rowValue:Record<string,unknown>,fromCache:boolean):Promise<CadastralOperationResult>{
  const requestId=String(rowValue.id);const [{data:unitRows},{data:holderRows},{data:documentRows}]=await Promise.all([db.from("cadastral_property_units").select("id,provider_property_id,section,urban_section,sheet,parcel,subaltern,address,census_zone,category,class,consistency,cadastral_income,registry_lot,acquired_at").eq("source_request_id",requestId),db.from("cadastral_ownership_rights").select("id,holder_type,first_name,last_name,company_name,tax_code,right_type_original,share_original,linked_subject_id,property_unit_id").eq("source_request_id",requestId),db.from("cadastral_documents").select("id").eq("cadastral_request_id",requestId).limit(1)]);
  const units=(Array.isArray(unitRows)?unitRows:[]).map(value=>{const item=record.parse(value);return{id:String(item.id),providerPropertyId:String(item.provider_property_id),section:text(item.section),urbanSection:text(item.urban_section),sheet:String(item.sheet),parcel:String(item.parcel),subaltern:text(item.subaltern),address:text(item.address),censusZone:text(item.census_zone),category:text(item.category),class:text(item.class),consistency:text(item.consistency),cadastralIncome:text(item.cadastral_income),registryLot:text(item.registry_lot),acquiredAt:text(item.acquired_at)}});
  const holders=await Promise.all((Array.isArray(holderRows)?holderRows:[]).map<Promise<CadastralHolder>>(async value=>{const item=record.parse(value);const taxCode=text(item.tax_code);let possibleSubjectId:string|undefined;if(taxCode&&!text(item.linked_subject_id)){const normalized=taxCode.replace(/[^a-zA-Z0-9]/g,"").toUpperCase();const {data}=await db.from("subjects").select("id").eq("tax_code",normalized).limit(1);if(Array.isArray(data)&&data[0])possibleSubjectId=String(record.parse(data[0]).id)}return{id:String(item.id),holderType:item.holder_type==="PRIVATO"||item.holder_type==="AZIENDA"?item.holder_type:"NON_DETERMINATO",firstName:text(item.first_name),lastName:text(item.last_name),companyName:text(item.company_name),taxCode,rightTypeOriginal:text(item.right_type_original),shareOriginal:text(item.share_original),linkedSubjectId:text(item.linked_subject_id),possibleSubjectId}}));
  return{requestId,providerRequestId:text(rowValue.provider_request_id),operationType:rowValue.operation_type as CadastralOperationType,status:rowValue.status as CadastralOperationResult["status"],fromCache,requestedAt:String(rowValue.requested_at),completedAt:text(rowValue.completed_at),units,holders,documentId:Array.isArray(documentRows)&&documentRows[0]?String(record.parse(documentRows[0]).id):undefined,error:text(rowValue.error_message)};
}

async function finish(db:Db,rowValue:Record<string,unknown>,context:CadastralContext,state:ProviderRequestState,selectedUnit?:CadastralPropertyUnit){
  const status=state.status;const completedAt=status==="COMPLETED"?new Date().toISOString():null;const {error}=await db.from("cadastral_requests").update({provider_request_id:state.providerRequestId,status,result:state.raw,completed_at:completedAt,error_code:null,error_message:null}).eq("id",String(rowValue.id));if(error)throw new Error(error.message);
  if(status==="COMPLETED")await saveCompletedData(db,String(rowValue.id),text(rowValue.census_record_id),context,state,selectedUnit);
  const {data}=await db.from("cadastral_requests").select("*").eq("id",String(rowValue.id)).single();return toResult(db,record.parse(data),false);
}

async function begin(operationType:CadastralOperationType,parameters:Record<string,unknown>,context:CadastralContext,refresh:boolean,call:(provider:ReturnType<typeof cadastralDataProvider>)=>Promise<ProviderRequestState>,selectedUnit?:CadastralPropertyUnit){
  if(!hasSupabaseEnvironment())throw new Error("Database Supabase LAB non configurato.");const db=await createClient();const userId=await authorize(db);const hash=requestHash(parameters);
  if(!refresh){const {data}=await db.from("cadastral_requests").select("*").eq("provider","OPENAPI_CATASTO").eq("operation_type",operationType).eq("parameters_hash",hash).eq("status","COMPLETED").order("completed_at",{ascending:false}).limit(1);if(Array.isArray(data)&&data[0])return toResult(db,record.parse(data[0]),true)}
  const {data:active}=await db.from("cadastral_requests").select("*").eq("provider","OPENAPI_CATASTO").eq("operation_type",operationType).eq("parameters_hash",hash).in("status",["CREATED","IN_PROGRESS"]).limit(1);if(Array.isArray(active)&&active[0])return toResult(db,record.parse(active[0]),true);
  const {data:created,error:createError}=await db.from("cadastral_requests").insert({census_record_id:context.recordId??null,operation_type:operationType,canonical_parameters:parameters,parameters_hash:hash,requested_by:userId,status:"CREATED",estimated_cost:paidCadastralServicePrice(operationType).amount}).select("*").single();if(createError){if(createError.message.toLowerCase().includes("duplicate")){const {data:concurrent}=await db.from("cadastral_requests").select("*").eq("provider","OPENAPI_CATASTO").eq("operation_type",operationType).eq("parameters_hash",hash).in("status",["CREATED","IN_PROGRESS"]).limit(1);if(Array.isArray(concurrent)&&concurrent[0])return toResult(db,record.parse(concurrent[0]),true)}throw new Error(createError.message)}const requestRow=record.parse(created);
  try{return await finish(db,requestRow,context,await call(cadastralDataProvider()),selectedUnit)}catch(error){const failure=providerMessage(error);await db.from("cadastral_requests").update({status:"FAILED",error_code:failure.code,error_message:failure.message,completed_at:new Date().toISOString()}).eq("id",String(requestRow.id));throw new Error(failure.message)}
}

export async function requestPropertyUnits(input:{recordId?:string;context?:CadastralContext;refresh?:boolean}){const db=await createClient();await authorize(db);const context=input.recordId?await contextForRecord(db,input.recordId):contextSchema.parse(input.context);const parameters={tipo_catasto:"F",provincia:context.provinceCode,comune:context.municipality,codice_comune:context.municipalityCode,sezione:context.section,foglio:context.sheet,particella:context.parcel};return begin("ELENCO_IMMOBILI",parameters,context,Boolean(input.refresh),provider=>provider.requestPropertyUnits(context))}
async function unitAndContext(db:Db,input:{recordId?:string;context?:CadastralContext;unitId:string}){const {data,error}=await db.from("cadastral_property_units").select("*").eq("id",input.unitId).single();if(error)throw new Error(error.message);const item=record.parse(data);const context=input.recordId?await contextForRecord(db,input.recordId):input.context?contextSchema.parse(input.context):contextSchema.parse({provinceCode:item.province_code,municipality:item.municipality_name,municipalityCode:item.municipality_cadastral_code,section:item.section,sheet:item.sheet,parcel:item.parcel});const unit:CadastralPropertyUnit={id:String(item.id),providerPropertyId:String(item.provider_property_id),section:text(item.section),sheet:String(item.sheet),parcel:String(item.parcel),subaltern:text(item.subaltern)};return{context,unit}}
export async function requestPropertyHolders(input:{recordId?:string;context?:CadastralContext;unitId:string;refresh?:boolean}){const db=await createClient();await authorize(db);const {context,unit}=await unitAndContext(db,input);const parameters={id_immobile:unit.providerPropertyId,tipo_catasto:"F",provincia:context.provinceCode,comune:context.municipality,codice_comune:context.municipalityCode,sezione:unit.section??context.section,foglio:unit.sheet,particella:unit.parcel,subalterno:unit.subaltern};return begin("PROSPETTO_CATASTALE",parameters,context,Boolean(input.refresh),provider=>provider.requestPropertyHolders(context,unit),unit)}
async function storeOrdinaryReport(db:Db,result:CadastralOperationResult,recordId?:string){if(result.status!=="COMPLETED"||!result.providerRequestId||result.documentId)return result;const bytes=await cadastralDataProvider().downloadOrdinaryReport(result.providerRequestId);const path=`${result.requestId}/visura-ordinaria.pdf`;const upload=await db.storage.from("cadastral-documents").upload(path,bytes,{contentType:"application/pdf",upsert:false});if(upload.error&&!upload.error.message.toLowerCase().includes("already exists"))throw new Error(upload.error.message);const {data,error}=await db.from("cadastral_documents").upsert({cadastral_request_id:result.requestId,census_record_id:recordId??null,provider_document_id:result.providerRequestId,document_type:"VISURA_ORDINARIA",storage_path:path,mime_type:"application/pdf",byte_size:bytes.byteLength},{onConflict:"cadastral_request_id"}).select("id").single();if(error)throw new Error(error.message);return{...result,documentId:String(record.parse(data).id)}}
export async function requestOrdinaryReport(input:{recordId?:string;context?:CadastralContext;unitId:string;refresh?:boolean}){const db=await createClient();await authorize(db);const {context,unit}=await unitAndContext(db,input);const result=await begin("VISURA_ORDINARIA",{entita:"immobile",id_immobile:unit.providerPropertyId,tipo_visura:"ordinaria",provincia:context.provinceCode,comune:context.municipality,codice_comune:context.municipalityCode,sezione:unit.section??context.section,foglio:unit.sheet,particella:unit.parcel,subalterno:unit.subaltern},context,Boolean(input.refresh),provider=>provider.requestOrdinaryReport(unit.providerPropertyId),unit);return storeOrdinaryReport(db,result,input.recordId)}
async function storePlanimetricElaboration(db:Db,result:CadastralOperationResult,recordId?:string){if(result.status!=="COMPLETED"||!result.providerRequestId||result.documentId)return result;const bytes=await cadastralDataProvider().downloadPlanimetricElaboration(result.providerRequestId);const path=`${result.requestId}/elaborato-planimetrico.pdf`;const upload=await db.storage.from("cadastral-documents").upload(path,bytes,{contentType:"application/pdf",upsert:false});if(upload.error&&!upload.error.message.toLowerCase().includes("already exists"))throw new Error(upload.error.message);const {data,error}=await db.from("cadastral_documents").upsert({cadastral_request_id:result.requestId,census_record_id:recordId??null,provider_document_id:result.providerRequestId,document_type:"ELABORATO_PLANIMETRICO",storage_path:path,mime_type:"application/pdf",byte_size:bytes.byteLength},{onConflict:"cadastral_request_id"}).select("id").single();if(error)throw new Error(error.message);return{...result,documentId:String(record.parse(data).id)}}
export async function requestPlanimetricElaboration(input:{recordId?:string;context?:CadastralContext;unitId:string;refresh?:boolean}){const db=await createClient();await authorize(db);const {context,unit}=await unitAndContext(db,input);const result=await begin("ELABORATO_PLANIMETRICO",{tipo_catasto:"F",provincia:context.provinceCode,comune:context.municipality,codice_comune:context.municipalityCode,sezione:unit.section??context.section,foglio:unit.sheet,particella:unit.parcel,subalterno:unit.subaltern},context,Boolean(input.refresh),provider=>provider.requestPlanimetricElaboration(context),unit);return storePlanimetricElaboration(db,result,input.recordId)}

export async function pollCadastralRequest(requestId:string){
  const db=await createClient();await authorize(db);const {data,error}=await db.from("cadastral_requests").select("*").eq("id",requestId).single();if(error)throw new Error(error.message);const rowValue=record.parse(data);const persist=async(result:CadastralOperationResult)=>rowValue.operation_type==="VISURA_ORDINARIA"?storeOrdinaryReport(db,result,text(rowValue.census_record_id)):rowValue.operation_type==="ELABORATO_PLANIMETRICO"?storePlanimetricElaboration(db,result,text(rowValue.census_record_id)):result;if(rowValue.status!=="IN_PROGRESS"&&rowValue.status!=="CREATED")return persist(await toResult(db,rowValue,true));const providerRequestId=text(rowValue.provider_request_id);if(!providerRequestId)throw new Error("Identificativo provider mancante.");const parameters=record.parse(rowValue.canonical_parameters);const context=contextSchema.parse({recordId:text(rowValue.census_record_id),provinceCode:parameters.provincia??"NA",municipality:parameters.comune??"NA",municipalityCode:parameters.codice_comune??"NA",section:parameters.sezione,sheet:parameters.foglio??"NA",parcel:parameters.particella??"NA"});const selectedUnit=text(parameters.id_immobile)?{providerPropertyId:String(parameters.id_immobile),section:text(parameters.sezione),sheet:String(parameters.foglio??"NA"),parcel:String(parameters.particella??"NA"),subaltern:text(parameters.subalterno)}:undefined;const provider=cadastralDataProvider();const state=rowValue.operation_type==="VISURA_ORDINARIA"?await provider.getOrdinaryReport(providerRequestId):rowValue.operation_type==="ELABORATO_PLANIMETRICO"?await provider.getPlanimetricElaboration(providerRequestId):await provider.getRequest(providerRequestId);return persist(await finish(db,rowValue,context,state,selectedUnit));
}

export async function getRecordCadastralData(recordId:string){
  if(!hasSupabaseEnvironment())return{authorized:false,operations:[] as CadastralOperationResult[]};const db=await createClient();const {data:allowed}=await db.rpc("can_use_paid_cadastral_services_lab");const {data}=await db.from("cadastral_requests").select("*").eq("census_record_id",recordId).order("requested_at",{ascending:false}).limit(20);const operations=await Promise.all((Array.isArray(data)?data:[]).map(value=>toResult(db,record.parse(value),true)));return{authorized:allowed===true,operations};
}

export async function getCadastralAccess(){if(!hasSupabaseEnvironment())return false;const db=await createClient();const {data}=await db.rpc("can_use_paid_cadastral_services_lab");return data===true}

export async function getPaidServiceGovernance():Promise<PaidServiceGovernance>{
  if(!hasSupabaseEnvironment())return{authorized:false,canManage:false,operators:[],history:[]};const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)return{authorized:false,canManage:false,operators:[],history:[]};
  const {data:operatorRows,error:operatorError}=await db.from("operators").select("id,auth_user_id,display_name,can_use_paid_cadastral_services,can_manage_paid_cadastral_services,paid_services_monthly_budget,paid_services_per_request_limit").order("display_name");if(operatorError)throw new Error(operatorError.message);const rows:Array<Record<string,unknown>>=Array.isArray(operatorRows)?operatorRows.map(value=>record.parse(value)):[];const currentRow=rows.find(row=>String(row.auth_user_id)===user.id);const authorized=currentRow?.can_use_paid_cadastral_services===true;const canManage=currentRow?.can_manage_paid_cadastral_services===true;
  const monthStart=new Date();monthStart.setUTCDate(1);monthStart.setUTCHours(0,0,0,0);const {data:requestRows,error:requestError}=await db.from("cadastral_requests").select("id,requested_by,operation_type,status,requested_at,estimated_cost,known_cost,census_record_id,cadastral_documents(id)").gte("requested_at",monthStart.toISOString()).order("requested_at",{ascending:false}).limit(200);if(requestError)throw new Error(requestError.message);const requests:Array<Record<string,unknown>>=Array.isArray(requestRows)?requestRows.map(value=>record.parse(value)):[];const spending=new Map<string,number>();for(const item of requests){if(["CREATED","IN_PROGRESS","COMPLETED"].includes(String(item.status))){const amount=Number(item.known_cost??item.estimated_cost??0);spending.set(String(item.requested_by),(spending.get(String(item.requested_by))??0)+amount)}}
  const toSummary=(row:Record<string,unknown>):PaidServiceOperatorSummary=>{const monthSpend=spending.get(String(row.auth_user_id))??0;const monthlyBudget=Number(row.paid_services_monthly_budget??0);return{operatorId:String(row.id),name:String(row.display_name),monthlyBudget,perRequestLimit:Number(row.paid_services_per_request_limit??0),monthSpend,monthRemaining:Math.max(0,monthlyBudget-monthSpend),canManage:row.can_manage_paid_cadastral_services===true}};const visibleRows=canManage?rows:currentRow?[currentRow]:[];const operators=visibleRows.map(toSummary);
  const history:PaidServiceHistoryItem[]=requests.filter(item=>canManage||String(item.requested_by)===user.id).map(item=>{const docs=item.cadastral_documents;const first=Array.isArray(docs)?docs[0]:undefined;return{id:String(item.id),operatorName:rows.find(row=>String(row.auth_user_id)===String(item.requested_by))?.display_name?String(rows.find(row=>String(row.auth_user_id)===String(item.requested_by))?.display_name):"Operatore",operationType:String(item.operation_type) as PaidServiceHistoryItem["operationType"],status:String(item.status),requestedAt:String(item.requested_at),estimatedCost:Number(item.estimated_cost??0),knownCost:item.known_cost==null?undefined:Number(item.known_cost),documentId:first&&typeof first==="object"&&"id" in first?String((first as Record<string,unknown>).id):undefined,recordId:item.census_record_id==null?undefined:String(item.census_record_id)}});
  return{authorized,canManage,current:currentRow?toSummary(currentRow):undefined,operators,history};
}

export async function getCadastralContactPrefill(holderId:string):Promise<CadastralContactPrefill|undefined>{
  if(!hasSupabaseEnvironment())return undefined;const db=await createClient();const {data,error}=await db.from("cadastral_ownership_rights").select("holder_type,first_name,last_name,company_name,tax_code,right_type_original,share_original,cadastral_property_units(sheet,parcel,subaltern,category,census_record_id,census_records(census_zone_id,address_access_id,complex_id,address_accesses(street_id)))").eq("id",holderId).single();if(error)return undefined;const holder=record.parse(data);const unit=record.parse(holder.cadastral_property_units);const census=record.parse(unit.census_records??{});const right=(text(holder.right_type_original)??"").toLocaleLowerCase("it");const share=text(holder.share_original);const relationshipRole=right.includes("propriet")?(share&&share!=="1/1"&&share!=="1"?"Comproprietario":"Proprietario"):undefined;return{zoneId:text(census.census_zone_id),streetId:text(record.parse(census.address_accesses??{}).street_id),civicId:text(census.address_access_id),complexId:text(census.complex_id),subjectType:holder.holder_type==="AZIENDA"?"AZIENDA":"PRIVATO",firstName:text(holder.first_name),lastName:text(holder.last_name),companyName:text(holder.company_name),taxCode:text(holder.tax_code),relationshipRole,sheet:String(unit.sheet),parcel:String(unit.parcel),subaltern:text(unit.subaltern),cadastralCategory:text(unit.category)}
}

export async function getCadastralUnitPrefill(unitId:string):Promise<CadastralContactPrefill|undefined>{
  if(!hasSupabaseEnvironment())return undefined;const db=await createClient();const {data,error}=await db.from("cadastral_property_units").select("sheet,parcel,subaltern,category,class,consistency,cadastral_income,census_zone,registry_lot,address,census_record_id,census_records(census_zone_id,address_access_id,complex_id,address_accesses(street_id))").eq("id",unitId).single();if(error)return undefined;const unit=record.parse(data);const census=record.parse(unit.census_records??{});return{zoneId:text(census.census_zone_id),streetId:text(record.parse(census.address_accesses??{}).street_id),civicId:text(census.address_access_id),complexId:text(census.complex_id),subjectType:"PRIVATO",sheet:String(unit.sheet),parcel:String(unit.parcel),subaltern:text(unit.subaltern),cadastralCategory:text(unit.category),cadastralClass:text(unit.class),cadastralConsistency:text(unit.consistency),cadastralIncome:text(unit.cadastral_income),cadastralCensusZone:text(unit.census_zone),cadastralRegistryLot:text(unit.registry_lot),cadastralAddress:text(unit.address)}
}

export async function importCadastralUnitIntoContact(input:{recordId:string;unitId:string}){
  if(process.env.OPENAPI_CATASTO_ENV!=="production")throw new Error("Sandbox: i dati dimostrativi non possono essere importati nel contatto.");const db=await createClient();await authorize(db);const {data,error}=await db.from("cadastral_property_units").select("source_request_id,sheet,parcel,subaltern,category,class,consistency,cadastral_income,census_zone,registry_lot,address").eq("id",input.unitId).single();if(error)throw new Error(error.message);const unit=record.parse(data);const {error:updateError}=await db.from("census_records").update({sheet:unit.sheet,parcel:unit.parcel,subaltern:unit.subaltern,cadastral_category:unit.category,cadastral_class:unit.class,cadastral_consistency:unit.consistency,cadastral_income:unit.cadastral_income,cadastral_census_zone:unit.census_zone,cadastral_registry_lot:unit.registry_lot,cadastral_address:unit.address,cadastral_acquired_at:new Date().toISOString(),cadastral_source_request_id:unit.source_request_id}).eq("id",input.recordId);if(updateError)throw new Error(updateError.message);
}

export async function linkCadastralHolderToSubject(input:{recordId:string;holderId:string;subjectId:string}){const db=await createClient();await authorize(db);const {data,error:readError}=await db.from("cadastral_ownership_rights").select("right_type_original,share_original").eq("id",input.holderId).single();if(readError)throw new Error(readError.message);const right=record.parse(data);const {error}=await db.from("cadastral_ownership_rights").update({linked_subject_id:input.subjectId}).eq("id",input.holderId);if(error)throw new Error(error.message);const rightType=(text(right.right_type_original)??"").toLocaleLowerCase("it");if(rightType.includes("propriet")){const share=text(right.share_original);const role=share&&share!=="1"&&share!=="1/1"?"Comproprietario":"Proprietario";const linked=await db.rpc("link_subject_to_census_record_lab",{p_record_id:input.recordId,p_subject_id:input.subjectId,p_role:role});if(linked.error&&!linked.error.message.toLowerCase().includes("duplicate"))throw new Error(linked.error.message)}}

export async function getCadastralDocumentUrl(documentId:string){const db=await createClient();const {data,error}=await db.from("cadastral_documents").select("storage_path").eq("id",documentId).single();if(error)throw new Error(error.message);const signed=await db.storage.from("cadastral-documents").createSignedUrl(String(record.parse(data).storage_path),60);if(signed.error)throw new Error(signed.error.message);return signed.data.signedUrl}
