import { createHash } from "node:crypto";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";

const listingSchema=z.object({type:z.enum(["sale","rent"]),property_category:z.string().nullable().optional(),property_type:z.string().nullable().optional(),price:z.number(),price_per_sqm:z.number(),total_sqm:z.number(),rooms:z.number().int(),bedrooms:z.number().int(),bathrooms:z.number().int(),floor:z.string().nullable().optional(),has_elevator:z.boolean().nullable().optional(),heating:z.string().nullable().optional(),address:z.string().nullable().optional(),municipality:z.string().nullable().optional(),province:z.string().nullable().optional()});
const responseSchema=z.object({success:z.literal(true),data:z.array(listingSchema),message:z.string().optional(),error:z.nullable(z.number()).optional()});
export type Comparable=z.infer<typeof listingSchema>;

function env(){const token=process.env.OPENAPI_REALESTATE_TOKEN;if(!token)throw new Error("Token OpenAPI Real Estate non configurato.");const stage=process.env.OPENAPI_REALESTATE_ENV??"sandbox";if(stage!=="sandbox"&&stage!=="production")throw new Error("Ambiente OpenAPI Real Estate non valido.");return{token,baseUrl:stage==="production"?"https://realestate.openapi.com":"https://test.realestate.openapi.com"}}
async function authorize(){const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)throw new Error("Autenticazione richiesta.");const {data:allowed,error}=await db.rpc("can_use_paid_cadastral_services_lab");if(error||allowed!==true)throw new Error("Non sei autorizzato ai servizi OpenAPI a consumo.");return{db,userId:user.id}}
export async function requestComparables(input:{recordId:string;latitude:number;longitude:number;radius:number;surface?:number;rooms?:number}){
  const {db,userId}=await authorize();const parameters={latitude:input.latitude,longitude:input.longitude,search_radius:input.radius,limit:20,type:"sale",...(input.surface?{min_sqm:Math.max(1,Math.floor(input.surface*.7)),max_sqm:Math.ceil(input.surface*1.3)}:{}),...(input.rooms?{min_rooms:Math.max(1,Math.floor(input.rooms-1)),max_rooms:Math.ceil(input.rooms+1)}:{})};const hash=createHash("sha256").update(JSON.stringify(parameters)).digest("hex");
  const {data:cached,error:cacheError}=await db.from("realestate_comparable_requests").select("result").eq("provider","OPENAPI_REALESTATE").eq("parameters_hash",hash).maybeSingle();if(cacheError)throw new Error(cacheError.message);if(cached)return{fromCache:true,items:z.array(listingSchema).parse(cached.result)};
  const {token,baseUrl}=env();const query=new URLSearchParams(Object.entries(parameters).map(([key,value])=>[key,String(value)]));const response=await fetch(`${baseUrl}/IT-comparable?${query}`,{headers:{authorization:`Bearer ${token}`,accept:"application/json"},cache:"no-store"});if(response.status===401||response.status===403)throw new Error("Token Real Estate non valido o privo dello scope IT-comparable.");if(response.status===402)throw new Error("Credito OpenAPI Real Estate insufficiente.");const parsed=responseSchema.safeParse(await response.json());if(!response.ok||!parsed.success)throw new Error("Il provider Comparabili non ha restituito dati validi.");const {error}=await db.from("realestate_comparable_requests").insert({census_record_id:input.recordId,parameters,parameters_hash:hash,result:parsed.data.data,requested_by:userId});if(error)throw new Error(error.message);return{fromCache:false,items:parsed.data.data};
}
