import { notFound } from "next/navigation";
import { PageHeader } from "@/components/ui";
import { latestInterview } from "@/domain/census";
import { InterviewForm } from "@/features/census/interview-form";
import { hasSupabaseEnvironment } from "@/lib/supabase/server";
import { loadCensusData } from "@/services/census-data";

export default async function RecordPage({params,searchParams}:{params:Promise<{recordId:string}>;searchParams:Promise<{interviewCreated?:string}>}){
  const [{recordId},{interviewCreated},{records,operators}]=await Promise.all([params,searchParams,loadCensusData()]);
  const r=records.find(record=>record.id===recordId); if(!r) notFound(); const latest=latestInterview(r);
  return <><PageHeader eyebrow="Scheda censimento" title={`${r.lastName} ${r.firstName??""}`} description={`${r.zoneName} · ${r.streetName}, ${r.civicNumber}${r.civicExtension?`/${r.civicExtension}`:""}`}/>{interviewCreated==="1"&&<div className="success-banner">Intervista registrata nello storico.</div>}<div className="detail-grid"><section className="panel"><h2>Anagrafica</h2><dl><div><dt>Tipologia</dt><dd><span className="badge news">{r.contactType}</span></dd></div><div><dt>Telefono</dt><dd>{r.phone??"—"}</dd></div><div><dt>Responsabile</dt><dd>{r.responsibleOperatorName??"—"}</dd></div><div><dt>Ereditato</dt><dd>{r.inherited?"Sì":"No"}</dd></div><div><dt>Perizia immobiliare</dt><dd>{r.isAppraised?"Sì, flag manuale":"No"}</dd></div></dl></section><section className="panel"><h2>Immobile e catasto</h2><dl><div><dt>Porzione</dt><dd>{r.buildingScope}</dd></div><div><dt>Piano</dt><dd>{r.floorLabel??"—"}</dd></div><div><dt>Superficie</dt><dd>{r.surface?`${r.surface} m²`:"—"}</dd></div><div><dt>Complesso</dt><dd>{r.complexName??"—"}</dd></div><div><dt>Foglio / particella / sub.</dt><dd>{[r.sheet,r.parcel,r.subaltern].filter(Boolean).join(" / ")||"—"}</dd></div></dl></section></div><section className="panel history"><div className="panel-heading"><div><p className="eyebrow">Storico reale</p><h2>Interviste</h2></div><span>{r.interviews.length} eventi</span></div>{r.interviews.length?<div className="timeline">{[...r.interviews].sort((a,b)=>b.interviewDate.localeCompare(a.interviewDate)).map(interview=><article key={interview.id}><span className="timeline-dot"/><time>{interview.interviewDate}</time><div><strong>{interview.outcome??"Intervista"}</strong><p>{interview.response??"Nessuna risposta registrata"} · {interview.reason??"Nessun motivo"}</p><small>{interview.operatorName}{interview.recallDate?` · Ricontatto ${interview.recallDate}`:""}</small></div></article>)}</div>:<p className="muted">Mai contattato: nessuna intervista reale registrata.</p>}{latest&&<small className="muted">Ultima intervista derivata: {latest.interviewDate}</small>}</section><InterviewForm recordId={r.id} operators={operators} databaseMode={hasSupabaseEnvironment()}/></>;
}
