import { test, expect } from "@playwright/test";

test("login demo leads to census dashboard", async ({ page }) => { await page.goto("/login"); await page.getByRole("link",{name:/Entra nella demo LAB/}).click(); await expect(page.getByRole("heading",{name:"Censimento LAB"})).toBeVisible() });
test("contacts can be filtered", async ({ page }) => { await page.goto("/censimento/contatti"); await page.getByLabel("Ricerca rapida").fill("Via Roma"); await expect(page.getByText(/risultati/)).toBeVisible() });
test("never-contacted filter is based on interview absence", async ({ page }) => { await page.goto("/censimento/contatti"); await page.getByRole("button",{name:/Altri filtri/}).click(); await page.getByLabel("Stato contatto").selectOption("never"); await expect(page.getByText(/risultati/)).toBeVisible() });
test("street view fixes geographic context", async ({ page }) => { await page.goto("/censimento/zone/zone-1/vie/st-1"); await expect(page.getByText(/filtri Zona e Via non vengono richiesti/)).toBeVisible(); await expect(page.getByLabel("Zona")).toHaveCount(0) });
test("complex shows interiors", async ({ page }) => { await page.goto("/censimento/complessi/cx-1"); await expect(page.getByText("Complesso / Mostra interni")).toBeVisible(); await expect(page.getByText(/civici collegati/)).toBeVisible() });
test("new contact never includes interview fields", async ({ page }) => { await page.goto("/censimento/contatti/nuovo"); await page.getByLabel("Cognome *").fill("Test LAB"); await expect(page.getByRole("heading",{name:"Dati catastali manuali"})).toBeVisible(); await expect(page.getByText("Prima intervista")).toHaveCount(0) });
test("new zone offers both save flows", async ({ page }) => { await page.goto("/censimento/zone/nuova"); await expect(page.getByText("Salva e torna all’elenco")).toBeVisible(); await expect(page.getByRole("button",{name:/Salva e definisci le vie/})).toBeVisible() });
test("subject profile aggregates linked properties", async ({ page }) => { await page.goto("/censimento/soggetti/subject-1"); await expect(page.getByRole("heading",{name:"Ferri Anna"})).toBeVisible(); await expect(page.getByRole("heading",{name:"Proprietà collegate"})).toBeVisible() });
test("property profile lists linked subjects", async ({ page }) => { await page.goto("/censimento/contatti/rec-1"); await expect(page.getByRole("heading",{name:"Soggetti collegati"})).toBeVisible(); const linkedSubject=page.getByRole("article").filter({has:page.getByRole("link",{name:"Apri soggetto"})}); await expect(linkedSubject.getByText("Ferri Anna",{exact:true})).toBeVisible(); await expect(linkedSubject.getByRole("link",{name:"Apri soggetto"})).toBeVisible() });
