import { test, expect } from "@playwright/test";

async function isolateExternalMapServices(page: import("@playwright/test").Page) {
  await page.route("**/api/map/cadastral**", (route) => route.abort());
  await page.route("https://tile.openstreetmap.org/**", (route) => route.abort());
}

test("login demo leads to census dashboard", async ({ page }) => { await page.goto("/login"); await page.getByRole("link",{name:/Entra nella demo LAB/}).click(); await expect(page.getByRole("heading",{name:"Censimento LAB"})).toBeVisible() });
test("contacts can be filtered", async ({ page }) => { await page.goto("/censimento/contatti"); await page.getByLabel("Ricerca rapida").fill("Via Roma"); await expect(page.getByText(/risultati/)).toBeVisible() });
test("contacts list keeps open and adds direct edit",async({page})=>{await page.goto("/censimento/contatti");const firstRow=page.locator("tbody tr").first();await expect(firstRow.getByRole("link",{name:"Apri"})).toBeVisible();const edit=firstRow.getByRole("link",{name:"Modifica"});await expect(edit).toBeVisible();await expect(edit).toHaveAttribute("href",/\/modifica$/)});
test("operational filters and age are visible in the real contacts workflow", async ({ page }) => { await page.goto("/censimento/contatti"); await expect(page.getByRole("columnheader",{name:"Giorni dall'ultimo contatto"})).toBeVisible(); await page.getByLabel("Attività operativa").selectOption("never"); await expect(page.getByText(/risultati/)).toBeVisible(); await expect(page.getByText("Mai contattato").first()).toBeVisible() });
test("overdue and stale operational filters return matching contacts",async({page})=>{await page.goto("/censimento/contatti");await page.getByLabel("Attività operativa").selectOption("recallOverdue");await expect(page.getByText(/Ricontatto scaduto da/).first()).toBeVisible();await page.getByLabel("Attività operativa").selectOption("staleNews");await expect(page.getByText(/Non aggiornata da/).first()).toBeVisible()});
test("operational settings are reachable without changing the main navigation",async({page})=>{await page.goto("/censimento/contatti");await page.getByRole("link",{name:/Impostazioni operative/}).click();await expect(page.getByRole("heading",{name:"Impostazioni operative"})).toBeVisible();await expect(page.getByLabel("Giorni massimo senza aggiornamento di una Notizia")).toHaveValue("30")});
test("street view fixes geographic context", async ({ page }) => { await page.goto("/censimento/zone/zone-1/vie/st-1"); await expect(page.getByText(/filtri Zona e Via non vengono richiesti/)).toBeVisible(); await expect(page.getByLabel("Zona")).toHaveCount(0) });
test("complex shows interiors", async ({ page }) => { await page.goto("/censimento/complessi/cx-1"); await expect(page.getByText("Complesso / Mostra interni")).toBeVisible(); await expect(page.getByText(/civici collegati/)).toBeVisible() });
test("new contact keeps manual fields and exposes civic location status", async ({ page }) => { await page.goto("/censimento/contatti/nuovo"); await page.getByLabel("Zona di censimento *").selectOption("zone-1");await page.getByLabel("Via *").selectOption("st-1");await page.getByLabel("Civico *").selectOption("cv-1");await page.getByLabel("Cognome *").fill("Test LAB"); await expect(page.getByText("Posizione geografica verificata")).toBeVisible();await expect(page.getByRole("heading",{name:"Dati catastali manuali"})).toBeVisible(); await expect(page.getByText("Prima intervista")).toHaveCount(0) });
test("new zone offers both save flows", async ({ page }) => { await page.goto("/censimento/zone/nuova"); await expect(page.getByText("Salva e torna all’elenco")).toBeVisible(); await expect(page.getByRole("button",{name:/Salva e definisci le vie/})).toBeVisible() });
test("main navigation keeps the census contact workflow", async ({ page }) => { await page.goto("/"); const navigation=page.getByRole("navigation"); await expect(navigation.getByRole("link",{name:"Contatti"})).toBeVisible(); await expect(navigation.getByRole("link",{name:"Nuovo contatto"})).toBeVisible(); await expect(navigation.getByRole("link",{name:"Soggetti"})).toHaveCount(0); await expect(navigation.getByRole("link",{name:"Proprietà"})).toHaveCount(0) });
test("contact profile keeps interviews scoped and exposes edit and delete actions", async ({ page }) => { await page.goto("/censimento/contatti/rec-1"); await expect(page.getByText("Scheda contatto")).toBeVisible(); await expect(page.getByRole("link",{name:"Modifica contatto"})).toBeVisible(); await expect(page.getByRole("button",{name:"Elimina contatto"})).toBeVisible(); await expect(page.getByRole("heading",{name:"Altri immobili / contesti collegati"})).toBeVisible(); await expect(page.getByRole("heading",{name:"Interviste"})).toBeVisible();await expect(page.getByRole("heading",{name:"Non associati"})).toBeVisible();await expect(page.getByRole("button",{name:"Individua particella sulla mappa"})).toBeVisible() });
test("contact edit page preloads the contact and preserves geographic management",async({page})=>{await page.goto("/censimento/contatti/rec-1/modifica");await expect(page.getByRole("heading",{name:"Modifica contatto"})).toBeVisible();await expect(page.getByLabel("Cognome *")).toHaveValue("Ferri");await expect(page.getByLabel("Zona di censimento *")).toHaveValue("zone-1");await expect(page.getByText("Posizione geografica verificata")).toBeVisible();await expect(page.getByRole("button",{name:"Correggi sulla mappa"})).toBeVisible();await expect(page.getByRole("button",{name:"Salva modifiche"})).toBeVisible()});
test("GeoCensimento loads OpenLayers at full width below horizontal filters", async ({ page }) => { await isolateExternalMapServices(page); await page.goto("/geocensimento"); const filters=page.locator(".map-filters");const map=page.locator(".map-workspace");await expect(page.getByRole("heading",{name:"GeoCensimento"})).toBeVisible(); await expect(page.getByLabel("Mappa GeoCensimento")).toBeVisible(); await expect(page.getByText(/OpenStreetMap contributors/)).toBeVisible(); await expect(page.getByText(/da verificare.*non localizzati/)).toBeVisible(); await expect(page.locator(".service-state")).toContainText(/cartografia catastale|sovrapposizione catastale/i);const filterBox=await filters.boundingBox();const mapBox=await map.boundingBox();expect(filterBox).not.toBeNull();expect(mapBox).not.toBeNull();expect(mapBox!.y).toBeGreaterThan(filterBox!.y+filterBox!.height-2);expect(Math.abs(mapBox!.width-filterBox!.width)).toBeLessThan(3) });
test("cadastral click renders a structured territory-safe detail card",async({page})=>{await page.route("https://tile.openstreetmap.org/**",route=>route.abort());await page.route("**/api/map/cadastral**",route=>{const request=new URL(route.request().url()).searchParams.get("REQUEST")?.toLowerCase();if(request==="getfeatureinfo")return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({feature:{municipalityCode:"A944",sheet:"12",parcel:"88",featureType:"PARTICELLA"}})});return route.abort()});await page.goto("/geocensimento");const map=page.getByLabel("Mappa GeoCensimento");const box=await map.boundingBox();expect(box).not.toBeNull();await page.mouse.click(box!.x+box!.width-40,box!.y+100);const card=page.locator(".cadastral-detail-card");await expect(card).toBeVisible();await expect(card).toContainText("Catasto ufficiale");await expect(card).toContainText("Bologna");await expect(card).toContainText("A944");await expect(card).toContainText("PARTICELLA")});
test("street context opens GeoCensimento with stable URL filters", async ({ page }) => { await isolateExternalMapServices(page); await page.goto("/censimento/zone/zone-1/vie/st-1"); await page.getByRole("link",{name:"Visualizza in GeoCensimento"}).first().click(); await expect(page).toHaveURL(/geocensimento\?zone=zone-1&street=st-1/); await expect(page.getByLabel("Zona mappa")).toHaveValue("zone-1"); await expect(page.getByLabel("Via mappa")).toHaveValue("st-1") });
test("changing zone clears the dependent street filter", async ({ page }) => { await isolateExternalMapServices(page); await page.goto("/geocensimento?zone=zone-1&street=st-1"); await page.getByLabel("Zona mappa").selectOption("zone-2"); await expect(page.getByLabel("Via mappa")).toHaveValue(""); await expect(page).toHaveURL(/zone=zone-2/); await expect(page).not.toHaveURL(/street=/) });
