import { test, expect } from "@playwright/test";

async function isolateExternalMapServices(page: import("@playwright/test").Page) {
  await page.route("**/api/map/cadastral**", (route) => route.abort());
  await page.route("https://tile.openstreetmap.org/**", (route) => route.abort());
}

test("login demo leads to census dashboard", async ({ page }) => { await page.goto("/login"); await page.getByRole("link",{name:/Entra nella demo LAB/}).click(); await expect(page.getByRole("heading",{name:"Censimento LAB"})).toBeVisible() });
test("contacts can be filtered", async ({ page }) => { await page.goto("/censimento/contatti"); await page.getByLabel("Ricerca rapida").fill("Via Roma"); await expect(page.getByText(/risultati/)).toBeVisible() });
test("operational filters and age are visible in the real contacts workflow", async ({ page }) => { await page.goto("/censimento/contatti"); await expect(page.getByRole("columnheader",{name:"Giorni dall'ultimo contatto"})).toBeVisible(); await page.getByLabel("Attività operativa").selectOption("never"); await expect(page.getByText(/risultati/)).toBeVisible(); await expect(page.getByText("Mai contattato").first()).toBeVisible() });
test("overdue and stale operational filters return matching contacts",async({page})=>{await page.goto("/censimento/contatti");await page.getByLabel("Attività operativa").selectOption("recallOverdue");await expect(page.getByText(/Ricontatto scaduto da/).first()).toBeVisible();await page.getByLabel("Attività operativa").selectOption("staleNews");await expect(page.getByText(/Non aggiornata da/).first()).toBeVisible()});
test("operational settings are reachable without changing the main navigation",async({page})=>{await page.goto("/censimento/contatti");await page.getByRole("link",{name:/Impostazioni operative/}).click();await expect(page.getByRole("heading",{name:"Impostazioni operative"})).toBeVisible();await expect(page.getByLabel("Giorni massimo senza aggiornamento di una Notizia")).toHaveValue("30")});
test("street view fixes geographic context", async ({ page }) => { await page.goto("/censimento/zone/zone-1/vie/st-1"); await expect(page.getByText(/filtri Zona e Via non vengono richiesti/)).toBeVisible(); await expect(page.getByLabel("Zona")).toHaveCount(0) });
test("complex shows interiors", async ({ page }) => { await page.goto("/censimento/complessi/cx-1"); await expect(page.getByText("Complesso / Mostra interni")).toBeVisible(); await expect(page.getByText(/civici collegati/)).toBeVisible() });
test("new contact never includes interview fields", async ({ page }) => { await page.goto("/censimento/contatti/nuovo"); await page.getByLabel("Cognome *").fill("Test LAB"); await expect(page.getByRole("heading",{name:"Dati catastali manuali"})).toBeVisible(); await expect(page.getByText("Prima intervista")).toHaveCount(0) });
test("new zone offers both save flows", async ({ page }) => { await page.goto("/censimento/zone/nuova"); await expect(page.getByText("Salva e torna all’elenco")).toBeVisible(); await expect(page.getByRole("button",{name:/Salva e definisci le vie/})).toBeVisible() });
test("main navigation keeps the census contact workflow", async ({ page }) => { await page.goto("/"); const navigation=page.getByRole("navigation"); await expect(navigation.getByRole("link",{name:"Contatti"})).toBeVisible(); await expect(navigation.getByRole("link",{name:"Nuovo contatto"})).toBeVisible(); await expect(navigation.getByRole("link",{name:"Soggetti"})).toHaveCount(0); await expect(navigation.getByRole("link",{name:"Proprietà"})).toHaveCount(0) });
test("contact profile keeps interviews scoped and shows other contexts", async ({ page }) => { await page.goto("/censimento/contatti/rec-1"); await expect(page.getByText("Scheda contatto")).toBeVisible(); await expect(page.getByRole("heading",{name:"Altri immobili / contesti collegati"})).toBeVisible(); await expect(page.getByRole("heading",{name:"Interviste"})).toBeVisible() });
test("GeoCensimento loads OpenLayers with attribution and explicit missing-location counts", async ({ page }) => { await isolateExternalMapServices(page); await page.goto("/geocensimento"); await expect(page.getByRole("heading",{name:"GeoCensimento"})).toBeVisible(); await expect(page.getByLabel("Mappa GeoCensimento")).toBeVisible(); await expect(page.getByText(/OpenStreetMap contributors/)).toBeVisible(); await expect(page.getByText(/civici non geolocalizzati/)).toBeVisible(); await expect(page.getByText(/Catasto:/)).toBeVisible() });
test("street context opens GeoCensimento with stable URL filters", async ({ page }) => { await isolateExternalMapServices(page); await page.goto("/censimento/zone/zone-1/vie/st-1"); await page.getByRole("link",{name:"Visualizza in GeoCensimento"}).first().click(); await expect(page).toHaveURL(/geocensimento\?zone=zone-1&street=st-1/); await expect(page.getByLabel("Zona mappa")).toHaveValue("zone-1"); await expect(page.getByLabel("Via mappa")).toHaveValue("st-1") });
test("changing zone clears the dependent street filter", async ({ page }) => { await isolateExternalMapServices(page); await page.goto("/geocensimento?zone=zone-1&street=st-1"); await page.getByLabel("Zona mappa").selectOption("zone-2"); await expect(page.getByLabel("Via mappa")).toHaveValue(""); await expect(page).toHaveURL(/zone=zone-2/); await expect(page).not.toHaveURL(/street=/) });
