import nextEnv from "@next/env";
import { expect, test } from "@playwright/test";
import { forwardLabAuth } from "./lab-auth-proxy";

nextEnv.loadEnvConfig(process.cwd());
const street="/censimento/zone/664a2d00-7450-48d8-86b5-07862ac7c269/vie/cd3bc43e-d541-4777-9bb8-d0fea32067e4";

test("authenticated Case Geska is a single expandable Street item",async({page})=>{
  test.setTimeout(120000);
  const email=process.env.ANNCSU_TEST_EMAIL,password=process.env.ANNCSU_TEST_PASSWORD;
  expect(email).toBeTruthy();expect(password).toBeTruthy();
  await forwardLabAuth(page);
  await page.goto("/login");
  await page.getByLabel("E-mail").fill(email!);await page.getByLabel("Password").fill(password!);
  await page.getByRole("button",{name:"Accedi"}).click();
  await expect(page.getByRole("heading",{name:"Performance e attività",exact:true})).toBeVisible({timeout:30000});
  const opened=performance.now();await page.goto(`${street}?q=Geska`);
  const card=page.getByRole("article",{name:"Complesso Case Geska"});
  await expect(card).toBeVisible();const openMs=Math.round(performance.now()-opened);
  await expect(card.getByText("13 unità dichiarate")).toBeVisible();
  await expect(card.getByText("2 contatti censiti")).toBeVisible();
  await expect(page.locator("tbody tr")).toHaveCount(1);
  const photo=card.getByRole("img",{name:"Foto del complesso Case Geska"});
  await expect(photo).toBeVisible();
  await expect.poll(()=>photo.evaluate(img=>(img as HTMLImageElement).complete&&(img as HTMLImageElement).naturalWidth>0)).toBe(true);
  await page.screenshot({path:"test-results/street-case-geska-desktop.png",fullPage:true,caret:"initial"});
  const expanded=performance.now();await card.getByRole("button",{name:/Mostra interni/}).click();
  await expect(card.getByText("Rosi Davide")).toBeVisible();
  await expect(card.getByText("Rosi Monica")).toBeVisible();
  const expandMs=Math.round(performance.now()-expanded);
  await expect(card.getByRole("link",{name:"Apri contatto"})).toHaveCount(2);
  await page.screenshot({path:"test-results/street-case-geska-expanded.png",fullPage:true,caret:"initial"});
  await card.getByRole("link",{name:"Apri contatto"}).first().click();
  await expect(page.getByText("Scheda contatto")).toBeVisible();
  await page.goBack();
  await expect(card).toBeVisible();
  await card.getByRole("button",{name:/Mostra interni/}).click();
  await card.getByRole("button",{name:/Nascondi interni/}).click();
  await expect(card.getByRole("button",{name:/Mostra interni/})).toBeVisible();
  await card.getByRole("link",{name:"Apri complesso"}).click();
  await expect(page.getByRole("heading",{name:"Case Geska"})).toBeVisible();
  await page.goto(`${street}?q=Rosi`);
  await expect(card).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  await page.goto(`${street}?q=Geska`);
  await expect(card).toBeVisible();
  await expect.poll(()=>card.getByRole("img",{name:"Foto del complesso Case Geska"}).evaluate(img=>(img as HTMLImageElement).complete&&(img as HTMLImageElement).naturalWidth>0)).toBe(true);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:"test-results/street-case-geska-mobile.png",fullPage:true,caret:"initial"});
  console.log(JSON.stringify({streetOpenMs:openMs,complexExpandMs:expandMs}));
});

test("New Contact keeps the property draft when identity is missing",async({page})=>{
  const email=process.env.ANNCSU_TEST_EMAIL,password=process.env.ANNCSU_TEST_PASSWORD;
  expect(email).toBeTruthy();expect(password).toBeTruthy();await forwardLabAuth(page);
  await page.goto("/login");await page.getByLabel("E-mail").fill(email!);await page.getByLabel("Password").fill(password!);
  await page.getByRole("button",{name:"Accedi"}).click();
  await expect(page.getByRole("heading",{name:"Performance e attività",exact:true})).toBeVisible({timeout:30000});
  await page.goto("/censimento/contatti/nuovo?zoneId=664a2d00-7450-48d8-86b5-07862ac7c269&streetId=cd3bc43e-d541-4777-9bb8-d0fea32067e4");
  await page.getByLabel("Cerca accesso").fill("270");
  await expect(page.getByLabel("Civico *").locator("option")).not.toHaveCount(1);
  await page.getByLabel("Civico *").selectOption({index:1});
  const selected=await page.getByLabel("Civico *").inputValue();
  await page.getByLabel("Interno").fill("4");
  await page.getByLabel("Foglio").fill("99");
  await page.getByLabel("Ruolo nel contesto *").selectOption("Proprietario");
  await page.getByRole("button",{name:"Salva contatto"}).click();
  await expect(page.getByRole("alert").filter({hasText:"Completa l’anagrafica"})).toBeVisible();
  await expect(page.getByLabel("Civico *")).toHaveValue(selected);
  await expect(page.getByLabel("Interno")).toHaveValue("4");
  await expect(page.getByLabel("Foglio")).toHaveValue("99");
});
