"use client";

import { useActionState, useMemo, useRef, useState } from "react";
import { useFormStatus } from "react-dom";
import { AlertTriangle, Save } from "lucide-react";
import { z } from "zod";
import type { Country, Municipality, Operator, Province, Region, Street } from "@/domain/census";
import { createZoneAction } from "./actions";

interface Props { countries:Country[]; regions:Region[]; provinces:Province[]; municipalities?:Municipality[]; operators:Operator[]; streets?:Street[]; databaseMode:boolean }

const municipalitiesResponseSchema=z.object({municipalities:z.array(z.object({id:z.string(),provinceId:z.string(),name:z.string(),istatCode:z.string().optional(),cadastralCode:z.string().optional()}))});
const streetsResponseSchema=z.object({streets:z.array(z.object({id:z.string(),municipalityId:z.string(),name:z.string(),municipality:z.string()}))});

function ZoneSubmitButtons({databaseMode}:{databaseMode:boolean}){const {pending}=useFormStatus();return <div className="button-row"><button className="button secondary" name="intent" value="list" disabled={pending||!databaseMode}>Salva e torna all’elenco</button><button className="button primary" name="intent" value="streets" disabled={pending||!databaseMode}><Save size={17}/>{pending?"Salvataggio…":"Salva e definisci le vie"}</button></div>}

export function ZoneForm({countries,regions,provinces,municipalities=[],operators,streets=[],databaseMode}:Props){
  const [state,action]=useActionState(createZoneAction,{});const [countryId,setCountryId]=useState("");const [regionId,setRegionId]=useState("");const [provinceId,setProvinceId]=useState("");const [municipalityId,setMunicipalityId]=useState("");const [availableMunicipalities,setAvailableMunicipalities]=useState<Municipality[]>([]);const [municipalitiesState,setMunicipalitiesState]=useState<"idle"|"loading"|"error">("idle");const [availableStreets,setAvailableStreets]=useState<Street[]>([]);const [streetsState,setStreetsState]=useState<"idle"|"loading"|"error">("idle");const municipalitiesRequest=useRef(0);const streetsRequest=useRef(0);
  const allowedRegions=regions.filter((region)=>region.countryId===countryId);const allowedProvinces=provinces.filter((province)=>province.regionId===regionId);const allowedStreets=useMemo(()=>availableStreets.filter((street)=>street.municipalityId===municipalityId),[availableStreets,municipalityId]);
  function selectProvince(nextProvinceId:string){const requestId=++municipalitiesRequest.current;setProvinceId(nextProvinceId);setMunicipalityId("");const embedded=municipalities.filter((municipality)=>municipality.provinceId===nextProvinceId);if(!nextProvinceId){setAvailableMunicipalities([]);setMunicipalitiesState("idle");return}if(embedded.length){setAvailableMunicipalities(embedded);setMunicipalitiesState("idle");return}setAvailableMunicipalities([]);setMunicipalitiesState("loading");void fetch(`/api/territory/municipalities?provinceId=${encodeURIComponent(nextProvinceId)}`).then(async(response)=>{if(!response.ok)throw new Error();return municipalitiesResponseSchema.parse(await response.json())}).then(({municipalities:loaded})=>{if(requestId!==municipalitiesRequest.current)return;setAvailableMunicipalities(loaded);setMunicipalitiesState("idle")}).catch(()=>{if(requestId===municipalitiesRequest.current)setMunicipalitiesState("error")})}
  function selectMunicipality(nextMunicipalityId:string){const requestId=++streetsRequest.current;setMunicipalityId(nextMunicipalityId);const embedded=streets.filter((street)=>street.municipalityId===nextMunicipalityId);if(!nextMunicipalityId){setAvailableStreets([]);setStreetsState("idle");return}if(embedded.length){setAvailableStreets(embedded);setStreetsState("idle");return}setAvailableStreets([]);setStreetsState("loading");void fetch(`/api/territory/streets?municipalityId=${encodeURIComponent(nextMunicipalityId)}`).then(async(response)=>{if(!response.ok)throw new Error();return streetsResponseSchema.parse(await response.json())}).then(({streets:loaded})=>{if(requestId!==streetsRequest.current)return;setAvailableStreets(loaded);setStreetsState("idle")}).catch(()=>{if(requestId===streetsRequest.current)setStreetsState("error")})}
  return <form className="record-form" action={action}>{state.error&&<div className="error-banner" role="alert"><AlertTriangle/>{state.error}</div>}
    <section className="form-section"><div className="section-title"><span>01</span><div><h2>Territorio e assegnazione</h2><p>Selezione gerarchica delle entità persistenti</p></div></div><div className="fields-grid">
      <label>Nazione *<select name="countryId" required value={countryId} onChange={(event)=>{setCountryId(event.target.value);setRegionId("");setProvinceId("");setMunicipalityId("")}}><option value="">Seleziona…</option>{countries.map((country)=><option value={country.id} key={country.id}>{country.name}</option>)}</select></label>
      <label>Regione *<select name="regionId" required value={regionId} disabled={!countryId} onChange={(event)=>{setRegionId(event.target.value);setProvinceId("");setMunicipalityId("")}}><option value="">Seleziona…</option>{allowedRegions.map((region)=><option value={region.id} key={region.id}>{region.name}</option>)}</select></label>
      <label>Provincia *<select name="provinceId" required value={provinceId} disabled={!regionId} onChange={(event)=>selectProvince(event.target.value)}><option value="">Seleziona…</option>{allowedProvinces.map((province)=><option value={province.id} key={province.id}>{province.name}</option>)}</select></label>
      <label>Comune *<select name="municipalityId" required value={municipalityId} disabled={!provinceId||municipalitiesState==="loading"} onChange={(event)=>selectMunicipality(event.target.value)}><option value="">{municipalitiesState==="loading"?"Caricamento comuni…":"Seleziona…"}</option>{availableMunicipalities.map((municipality)=><option value={municipality.id} key={municipality.id}>{municipality.name}</option>)}</select>{municipalitiesState==="error"&&<small className="form-error">Impossibile caricare i comuni. Riprova selezionando la provincia.</small>}</label>
      <label>Nome zona *<input name="name" required placeholder="es. Murri"/></label><label>Assegnatario *<select name="operatorId" required defaultValue=""><option value="">Seleziona…</option>{operators.map((operator)=><option value={operator.id} key={operator.id}>{operator.name}</option>)}</select></label>
    </div></section>
    <section className="form-section"><div className="section-title"><span>02</span><div><h2>Vie della zona</h2><p>Seleziona vie esistenti nel Comune oppure creane una nuova</p></div></div>{municipalityId?<>{streetsState==="loading"?<p className="muted">Caricamento vie…</p>:streetsState==="error"?<p className="form-error">Impossibile caricare le vie. Riprova selezionando il Comune.</p>:<div className="check-grid">{allowedStreets.map((street)=><label className="check-card" key={street.id}><input name="streetIds" value={street.id} type="checkbox"/><span>{street.name}<small>{street.municipality}</small></span></label>)}</div>}<label className="standalone-field">Nuova Via<input name="newStreetName" placeholder="Inserisci solo se non è già presente"/></label></>:<p className="muted">Seleziona prima il Comune.</p>}</section>
    <div className="form-footer"><span>{databaseMode?"Salvataggio nel database Supabase LAB":"Fallback demo in sola lettura"}</span><ZoneSubmitButtons databaseMode={databaseMode}/></div>
  </form>
}
