/* eslint-disable @next/next/no-img-element */
"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, Camera, Check, Image as ImageIcon, ScanText, Split, Trash2, Upload } from "lucide-react";
import { COMPLEX_PHOTO_BUCKET, duplicateProposalIds, type ComplexPhotoData, type DoorbellProposal } from "@/domain/complex-photos";
import { civicLabel, floorCodes, occupancies, qualifications, subjectDisplayName, type Civic, type Operator, type Subject } from "@/domain/census";
import { createClient } from "@/lib/supabase/client";
import { addManualDoorbellProposalAction, analyzeDoorbellPhotoAction, confirmDoorbellProposalsAction, createAcquisitionSessionAction, deleteComplexPhotoAction, mergeDoorbellProposalsAction, registerComplexPhotoAction, saveDoorbellProposalAction, splitDoorbellProposalAction, updateComplexPhotoAction } from "./actions";

type Props = ComplexPhotoData & { complexId: string; civics: Civic[]; operators: Operator[] };
const extensionFor = (type: string) => type === "image/jpeg" ? ".jpg" : type === "image/png" ? ".png" : ".webp";

export function ComplexPhotoManager({ complexId, photos, proposals: initialProposals, ocrConfigured, databaseMode, civics, operators }: Props) {
  const [proposals, setProposals] = useState(initialProposals); const [selected, setSelected] = useState<Set<string>>(new Set()); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [matches, setMatches] = useState<Record<string, Subject[]>>({});
  const duplicateIds = useMemo(() => duplicateProposalIds(proposals), [proposals]);
  const patchProposal = (proposalId: string, patch: Partial<DoorbellProposal>) => setProposals((current) => current.map((proposal) => proposal.id === proposalId ? { ...proposal, ...patch } : proposal));
  const toggle = (proposalId: string) => setSelected((current) => { const next = new Set(current); if (next.has(proposalId)) next.delete(proposalId); else next.add(proposalId); return next; });
  async function run(task: () => Promise<unknown>, success: string) { setBusy(true); setMessage(""); try { await task(); setMessage(success); } catch (error) { setMessage(error instanceof Error ? error.message : "Operazione non riuscita."); } finally { setBusy(false); } }
  async function upload(files: FileList | null, photoType: "COMPLEX" | "DOORBELL") {
    if (!files?.length || !databaseMode) return; await run(async () => {
      const sessionId = photoType === "DOORBELL" ? await createAcquisitionSessionAction(complexId) : undefined; const db = createClient();
      for (const file of Array.from(files)) {
        if (!["image/jpeg","image/png","image/webp"].includes(file.type) || file.size > 10_485_760) throw new Error("Sono ammesse immagini JPG, PNG o WebP fino a 10 MB.");
        const photoId = crypto.randomUUID(); const storagePath = `${complexId}/${photoId}${extensionFor(file.type)}`;
        const uploaded = await db.storage.from(COMPLEX_PHOTO_BUCKET).upload(storagePath, file, { contentType: file.type, upsert: false }); if (uploaded.error) throw new Error(uploaded.error.message);
        try { await registerComplexPhotoAction({ id: photoId, complexId, sessionId, photoType, storagePath, originalFilename: file.name, mimeType: file.type as "image/jpeg"|"image/png"|"image/webp", byteSize: file.size }); }
        catch (error) { await db.storage.from(COMPLEX_PHOTO_BUCKET).remove([storagePath]); throw error; }
      }
    }, photoType === "COMPLEX" ? "Foto del complesso caricate. Nessuna analisi OCR è stata avviata." : "Foto campanelli caricate. Avvia l'analisi esplicitamente quando sei pronto.");
  }
  async function findMatches(proposal: DoorbellProposal) {
    const query = (proposal.subjectType === "AZIENDA" ? proposal.companyName ?? "" : `${proposal.lastName ?? ""} ${proposal.firstName ?? ""}`).trim(); if (query.length < 2) return;
    const response = await fetch(`/api/census/subjects?q=${encodeURIComponent(query)}`); if (!response.ok) return; const body = await response.json() as { subjects?: Subject[] }; setMatches((current) => ({ ...current, [proposal.id]: body.subjects ?? [] }));
  }
  async function save(proposal: DoorbellProposal, status: "DRAFT"|"DISCARDED" = proposal.status === "DISCARDED" ? "DISCARDED" : "DRAFT") {
    await saveDoorbellProposalAction({ proposalId: proposal.id, complexId, subjectType: proposal.subjectType, firstName: proposal.firstName ?? "", lastName: proposal.lastName ?? "", companyName: proposal.companyName ?? "", existingSubjectId: proposal.existingSubjectId ?? "", civicId: proposal.civicId ?? "", buildingScope: proposal.buildingScope, staircase: proposal.staircase ?? "", unitIdentifier: proposal.unitIdentifier ?? "", floorCode: proposal.floorCode as (typeof floorCodes)[number] | "" | undefined, totalFloors: proposal.totalFloors, qualification: proposal.qualification ?? "", occupancy: proposal.occupancy ?? "", contactType: proposal.contactType, responsibleOperatorId: proposal.responsibleOperatorId ?? "", status });
  }
  async function confirmSelected() { await run(async () => { const chosen = proposals.filter((proposal) => selected.has(proposal.id) && proposal.status === "DRAFT"); for (const proposal of chosen) await save(proposal); const result = await confirmDoorbellProposalsAction(chosen.map((proposal) => proposal.id), complexId); if (!result.ok) throw new Error(result.error); }, "Contatti creati nel normale Elenco Contatti, senza interviste automatiche."); }
  async function bulkApply(field: "civicId"|"staircase"|"unitIdentifier"|"floorCode"|"qualification"|"occupancy", value: string) { setProposals((current) => current.map((proposal) => selected.has(proposal.id) ? { ...proposal, [field]: value || undefined } : proposal)); }

  const complexPhotos = photos.filter((photo) => photo.photoType === "COMPLEX"); const doorbellPhotos = photos.filter((photo) => photo.photoType === "DOORBELL"); const draftProposals = proposals.filter((proposal) => proposal.status !== "CREATED");
  return <section className="photo-workspace">
    <header><div><p className="eyebrow">Milestone 3</p><h2>Documentazione fotografica e acquisizione assistita</h2><p>Le foto e le proposte OCR non sono Contatti. Solo la conferma dell’operatore crea normali Contatti di censimento.</p></div></header>
    {message && <div className={message.includes("non") || message.includes("errore") ? "error-banner" : "success-banner"} role="status">{message}</div>}
    <div className="photo-columns">
      <PhotoCollection title="Foto del complesso" description="Facciate, ingressi e parti comuni. Nessun OCR automatico." icon={<ImageIcon/>} photos={complexPhotos} disabled={busy || !databaseMode} onUpload={(files) => upload(files,"COMPLEX")} onDelete={(id) => run(() => deleteComplexPhotoAction(id,complexId),"Foto eliminata dallo Storage privato.")} onUpdate={(photo) => run(() => updateComplexPhotoAction({ photoId: photo.id, complexId, caption: photo.caption, sortOrder: photo.sortOrder, isPrimary: photo.isPrimary }),"Dati foto aggiornati.")}/>
      <PhotoCollection title="Foto campanelli / citofoni" description="L'analisi legge soltanto testo e richiede sempre revisione umana." icon={<Camera/>} photos={doorbellPhotos} disabled={busy || !databaseMode} onUpload={(files) => upload(files,"DOORBELL")} onDelete={(id) => run(() => deleteComplexPhotoAction(id,complexId),"Foto eliminata dallo Storage privato.")} onUpdate={(photo) => run(() => updateComplexPhotoAction({ photoId: photo.id, complexId, caption: photo.caption, sortOrder: photo.sortOrder, isPrimary: false }),"Nota foto aggiornata.")} onAnalyze={(id) => run(async () => { const result = await analyzeDoorbellPhotoAction(id,complexId); if (!result.ok) throw new Error(result.error); },"Analisi completata: le proposte sono pronte per la revisione.")} onAddManual={(id)=>run(()=>addManualDoorbellProposalAction(id,complexId),"Proposta manuale aggiunta alla revisione.")} ocrConfigured={ocrConfigured}/>
    </div>
    {draftProposals.length > 0 && <section className="review-panel"><div className="review-heading"><div><p className="eyebrow">Revisione obbligatoria</p><h2>Proposte rilevate</h2><p>La confidence è soltanto un aiuto. Correggi ogni dato e scegli esplicitamente ruolo e contesto.</p></div><span>{selected.size} selezionate</span></div>
      <div className="bulk-toolbar"><strong>Applica ai selezionati</strong><select aria-label="Civico massivo" onChange={(event)=>bulkApply("civicId",event.target.value)}><option value="">Civico…</option>{civics.map((civic)=><option key={civic.id} value={civic.id}>{civicLabel(civic)}</option>)}</select><input aria-label="Scala massiva" placeholder="Scala" onBlur={(event)=>bulkApply("staircase",event.target.value)}/><input aria-label="Interno massivo" placeholder="Interno" onBlur={(event)=>bulkApply("unitIdentifier",event.target.value)}/><select aria-label="Piano massivo" onChange={(event)=>bulkApply("floorCode",event.target.value)}><option value="">Piano…</option>{floorCodes.map((floor)=><option key={floor}>{floor}</option>)}</select><select aria-label="Qualifica massiva" onChange={(event)=>bulkApply("qualification",event.target.value)}><option value="">Qualifica…</option>{qualifications.map((item)=><option key={item}>{item}</option>)}</select><select aria-label="Occupazione massiva" onChange={(event)=>bulkApply("occupancy",event.target.value)}><option value="">Occupazione…</option>{occupancies.map((item)=><option key={item}>{item}</option>)}</select></div>
      <div className="proposal-list">{draftProposals.map((proposal)=><article className={`proposal-card ${duplicateIds.has(proposal.id)?"duplicate":""}`} key={proposal.id}><div className="proposal-select"><input type="checkbox" checked={selected.has(proposal.id)} onChange={()=>toggle(proposal.id)} aria-label={`Seleziona ${proposal.sourceText}`}/><div><strong>{proposal.sourceText}</strong><small>{proposal.confidence == null?"confidence non disponibile":`${Math.round(proposal.confidence*100)}%`}</small></div>{duplicateIds.has(proposal.id)&&<span className="warning-chip">Possibile duplicato nella sessione</span>}</div>
        <div className="proposal-fields"><label>Tipo<select value={proposal.subjectType} onChange={(e)=>patchProposal(proposal.id,{subjectType:e.target.value as DoorbellProposal["subjectType"],existingSubjectId:undefined})}><option value="UNKNOWN">Da verificare</option><option value="PRIVATO">Privato</option><option value="AZIENDA">Azienda</option></select></label>{proposal.subjectType==="AZIENDA"?<label className="span-2">Ragione sociale<input value={proposal.companyName??""} onChange={(e)=>patchProposal(proposal.id,{companyName:e.target.value})}/></label>:<><label>Nome<input value={proposal.firstName??""} onChange={(e)=>patchProposal(proposal.id,{firstName:e.target.value})}/></label><label>Cognome<input value={proposal.lastName??""} onChange={(e)=>patchProposal(proposal.id,{lastName:e.target.value})}/></label></>}
          <label>Civico<select value={proposal.civicId??""} onChange={(e)=>patchProposal(proposal.id,{civicId:e.target.value})}><option value="">Seleziona…</option>{civics.map((civic)=><option key={civic.id} value={civic.id}>{civicLabel(civic)}</option>)}</select></label><label>Scala<input value={proposal.staircase??""} onChange={(e)=>patchProposal(proposal.id,{staircase:e.target.value})}/></label><label>Interno<input value={proposal.unitIdentifier??""} onChange={(e)=>patchProposal(proposal.id,{unitIdentifier:e.target.value})}/></label><label>Piano<select value={proposal.floorCode??""} onChange={(e)=>patchProposal(proposal.id,{floorCode:e.target.value})}><option value="">Seleziona…</option>{floorCodes.map((floor)=><option key={floor}>{floor}</option>)}</select></label><label>Qualifica<select value={proposal.qualification??""} onChange={(e)=>patchProposal(proposal.id,{qualification:e.target.value as DoorbellProposal["qualification"]})}><option value="">Non dedotta</option>{qualifications.map((item)=><option key={item}>{item}</option>)}</select></label><label>Occupazione<select value={proposal.occupancy??""} onChange={(e)=>patchProposal(proposal.id,{occupancy:e.target.value as DoorbellProposal["occupancy"]})}><option value="">Non indicata</option>{occupancies.map((item)=><option key={item}>{item}</option>)}</select></label><label>Operatore<select value={proposal.responsibleOperatorId??""} onChange={(e)=>patchProposal(proposal.id,{responsibleOperatorId:e.target.value})}><option value="">Non assegnato</option>{operators.map((operator)=><option key={operator.id} value={operator.id}>{operator.name}</option>)}</select></label></div>
        {matches[proposal.id]?.length ? <div className="match-list"><AlertTriangle size={16}/><span>Possibili corrispondenze, nessun collegamento automatico:</span>{matches[proposal.id].map((subject)=><button type="button" className={proposal.existingSubjectId===subject.id?"active":""} key={subject.id} onClick={()=>patchProposal(proposal.id,{existingSubjectId:subject.id})}>{subjectDisplayName(subject)} · Collega</button>)}<button type="button" onClick={()=>patchProposal(proposal.id,{existingSubjectId:undefined})}>Crea nuovo</button></div> : null}
        <div className="proposal-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>findMatches(proposal)}>Cerca corrispondenze</button><button type="button" className="button secondary" disabled={busy} onClick={()=>run(()=>save(proposal),"Correzione salvata.")}><Check size={15}/> Salva correzione</button><button type="button" className="button secondary" disabled={busy} onClick={()=>run(()=>splitDoorbellProposalAction(proposal.id,complexId),"Proposta separata: entrambe restano da revisionare.")}><Split size={15}/> Separa</button><button type="button" className="button danger" disabled={busy} onClick={()=>{patchProposal(proposal.id,{status:"DISCARDED"});void run(()=>save({...proposal,status:"DISCARDED"},"DISCARDED"),"Proposta scartata.")}}><Trash2 size={15}/> Scarta</button></div></article>)}</div>
      <div className="review-footer"><button className="button secondary" type="button" disabled={busy||selected.size<2} onClick={()=>{const [target,...sources]=[...selected];void run(async()=>{for(const source of sources)await mergeDoorbellProposalsAction(target,source,complexId)},"Proposte unite; le sorgenti OCR sono state conservate.")}}>Unisci selezionate</button><button className="button primary" type="button" disabled={busy||selected.size===0} onClick={confirmSelected}>Crea contatti selezionati</button></div>
    </section>}
  </section>;
}

function PhotoCollection({ title, description, icon, photos, disabled, onUpload, onDelete, onUpdate, onAnalyze, onAddManual, ocrConfigured=true }: { title:string;description:string;icon:React.ReactNode;photos:ComplexPhotoData["photos"];disabled:boolean;onUpload:(files:FileList|null)=>void;onDelete:(id:string)=>void;onUpdate:(photo:ComplexPhotoData["photos"][number])=>void;onAnalyze?:(id:string)=>void;onAddManual?:(id:string)=>void;ocrConfigured?:boolean }) {
  const [edits,setEdits]=useState<Record<string,{caption:string;sortOrder:number;isPrimary:boolean}>>({});
  return <section className="photo-collection"><div className="photo-title">{icon}<div><h3>{title}</h3><p>{description}</p></div></div><label className="upload-control"><Upload size={17}/> Carica immagini<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={disabled} onChange={(event)=>onUpload(event.target.files)}/></label>{onAnalyze&&!ocrConfigured&&<small className="ocr-offline">OCR non configurato: usa “Aggiungi manualmente” oppure conserva la foto finché il servizio locale non viene attivato.</small>}<div className="photo-list">{photos.map((photo)=>{const edit=edits[photo.id]??{caption:photo.caption??"",sortOrder:photo.sortOrder,isPrimary:photo.isPrimary};return <article key={photo.id}>{photo.signedUrl?<img src={photo.signedUrl} alt={photo.caption||photo.originalFilename}/>:<div className="image-placeholder"><ImageIcon/></div>}<div className="photo-info"><strong>{photo.originalFilename}</strong><small>{photo.processingStatus} · {(photo.byteSize/1024/1024).toFixed(1)} MB</small><input aria-label={`Nota ${photo.originalFilename}`} placeholder="Nota" value={edit.caption} onChange={(e)=>setEdits({...edits,[photo.id]:{...edit,caption:e.target.value}})}/><div><input aria-label={`Ordine ${photo.originalFilename}`} type="number" min="0" value={edit.sortOrder} onChange={(e)=>setEdits({...edits,[photo.id]:{...edit,sortOrder:Number(e.target.value)}})}/>{!onAnalyze&&<label><input type="checkbox" checked={edit.isPrimary} onChange={(e)=>setEdits({...edits,[photo.id]:{...edit,isPrimary:e.target.checked}})}/> Principale</label>}</div><div className="photo-actions"><button className="button secondary" type="button" disabled={disabled} onClick={()=>onUpdate({...photo,...edit})}>Salva</button>{onAddManual&&<button className="button secondary" type="button" disabled={disabled} onClick={()=>onAddManual(photo.id)}>Aggiungi manualmente</button>}{onAnalyze&&<button className="button primary" type="button" disabled={disabled||!ocrConfigured||photo.processingStatus==="PROCESSING"} onClick={()=>onAnalyze(photo.id)}><ScanText size={15}/> Analizza foto</button>}<button className="icon-button danger" aria-label={`Elimina ${photo.originalFilename}`} type="button" disabled={disabled} onClick={()=>onDelete(photo.id)}><Trash2 size={17}/></button></div>{photo.processingError&&<small className="form-error">{photo.processingError}</small>}</div></article>})}</div></section>;
}
