import Link from "next/link";
import { ArrowRight, Plus } from "lucide-react";
import { PageHeader } from "@/components/ui";
import { getZoneAccessCounts } from "@/repositories/territory-repository";
import { listZoneAddressAccesses, listZoneStreets } from "@/repositories/territory-repository";
import { loadCensusData } from "@/services/census-data";
import { ZoneDeleteButton } from "@/features/zones/zone-delete-button";

export default async function ZonesPage({searchParams}:{searchParams:Promise<{created?:string;q?:string;municipality?:string;operator?:string}>}){
  const [params,{records,zones}]=await Promise.all([searchParams,loadCensusData(["records","zones"])]);const needle=params.q?.trim().toLocaleLowerCase("it")??"";
  const counts=await Promise.all(zones.map(zone=>getZoneAccessCounts(zone.id)));
  const matches=await Promise.all(zones.map(async(zone,index)=>{if(params.municipality&&zone.municipalityId!==params.municipality||params.operator&&zone.operator.id!==params.operator)return null;if(!needle)return{zone,index};const [streets,accesses]=await Promise.all([listZoneStreets(zone.id),listZoneAddressAccesses(zone.id,200)]);return [zone.name,zone.municipality,zone.operator.name,...streets.map(s=>s.name),...accesses.map(a=>[a.civic,a.exponent,a.metric,a.progressivoSnc].filter(Boolean).join("/"))].join(" ").toLocaleLowerCase("it").includes(needle)?{zone,index}:null}));
  return <><PageHeader eyebrow="Territorio" title="Zone" description="Organizza le aree di lavoro e gli indirizzi da censire." action={<Link className="button primary" href="/censimento/zone/nuova"><Plus size={17}/> Nuova zona</Link>}/>{params.created==="1"&&<div className="success-banner">Zona salvata correttamente.</div>}<form className="filter-panel filter-primary" action="/censimento/zone"><label className="search-field">Cerca zona, via o civico<input name="q" defaultValue={params.q} placeholder="es. Piano di Mommio, Alceste Cima, 106/A"/></label><label>Comune<select name="municipality" defaultValue={params.municipality??""}><option value="">Tutti</option>{zones.map(z=><option key={z.municipalityId} value={z.municipalityId}>{z.municipality}</option>)}</select></label><label>Operatore<select name="operator" defaultValue={params.operator??""}><option value="">Tutti</option>{zones.map(z=><option key={z.operator.id} value={z.operator.id}>{z.operator.name}</option>)}</select></label><button className="button secondary">Cerca</button></form><section className="table-panel zone-list"><div className="table-scroll"><table><thead><tr><th>Zona</th><th>Comune</th><th>Operatore</th><th>Vie / indirizzi</th><th>Civici</th><th>Contatti</th><th>Azioni</th></tr></thead><tbody>{matches.filter((v):v is {zone:typeof zones[number];index:number}=>Boolean(v)).map(({zone,index})=>{const zoneRecords=records.filter(record=>record.zoneId===zone.id),count=counts[index];return <tr key={zone.id}><td><strong>{zone.name}</strong></td><td>{zone.municipality}</td><td>{zone.operator.name}</td><td>{count.streetCount}</td><td>{count.accessCount}</td><td>{zoneRecords.length}</td><td><div className="button-row"><Link className="row-action" href={`/censimento/zone/${zone.id}`}>Apri <ArrowRight size={14}/></Link><Link className="row-action" href={`/censimento/zone/${zone.id}/modifica`}>Modifica</Link><ZoneDeleteButton zoneId={zone.id}/></div></td></tr>})}</tbody></table></div></section></>;
}
