"use client";

import { useActionState, useMemo, useState } from "react";
import { useFormStatus } from "react-dom";
import { AlertTriangle, Database, Layers, Link2, Save } from "lucide-react";
import { z } from "zod";
import {
  cadastralCategories, canShowAppraisal, engagementTypes, floorCodes, occupancies, qualifications, subjectDisplayName,
  type BuildingScope, type CensusZone, type Civic, type Complex, type ContactType, type EngagementType, type Operator, type Street, type Subject, type SubjectType,
} from "@/domain/census";
import { civics as demoCivics, complexes as demoComplexes, operators as demoOperators, streets as demoStreets, subjects as demoSubjects, zones as demoZones } from "@/lib/demo-data";
import { createCensusRecordAction, type FormActionState } from "./actions";
import { CivicLocationPicker } from "./civic-location-picker";
import { CadastralPicker } from "./cadastral-picker";
import { DatePickerField } from "@/components/date-picker-field";
import type { CadastralFeatureInfo } from "@/services/cadastral-feature";
import type { CadastralContactPrefill } from "@/domain/cadastral-data";

interface ContactFormProps { zones?:CensusZone[];streets?:Street[];civics?:Civic[];complexes?:Complex[];operators?:Operator[];subjects?:Subject[];databaseMode?:boolean;prefill?:CadastralContactPrefill;formAction?:(state:FormActionState,data:FormData)=>Promise<FormActionState> }
const normalizeIdentifier=(value:string)=>value.trim().replace(/[^a-zA-Z0-9]/g,"").toUpperCase();
const subjectSearchResponseSchema=z.object({subjects:z.array(z.object({id:z.string(),subjectType:z.enum(["PRIVATO","AZIENDA"]),firstName:z.string().optional(),lastName:z.string().optional(),companyName:z.string().optional(),taxCode:z.string().optional(),vatNumber:z.string().optional(),phone:z.string().optional(),email:z.string().optional(),birthDate:z.string().optional(),notes:z.string().optional()}))});
function SubmitButton({databaseMode}:{databaseMode:boolean}){const {pending}=useFormStatus();return <button className="button primary" type="submit" disabled={pending||!databaseMode}><Save size={17}/>{pending?"Salvataggio…":"Salva contatto"}</button>}

export function ContactForm({zones=demoZones,streets=demoStreets,civics=demoCivics,complexes=demoComplexes,operators=demoOperators,subjects,databaseMode=false,prefill,formAction=createCensusRecordAction}:ContactFormProps){
  const embeddedSubjects=subjects??(databaseMode?[]:demoSubjects);
  const [state,action]=useActionState(formAction,{});const [zoneId,setZoneId]=useState(prefill?.zoneId??"");const [streetId,setStreetId]=useState(prefill?.streetId??"");const [civicId,setCivicId]=useState(prefill?.civicId??"");const [contactType,setContactType]=useState<ContactType>("Generico");const[engagementType,setEngagementType]=useState<EngagementType>("Nessuno");const [buildingScope,setBuildingScope]=useState<BuildingScope>(prefill?"Parte di edificio":"Intero edificio");
  const [locationPickerOpen,setLocationPickerOpen]=useState(false);const [locationOverride,setLocationOverride]=useState<{status:"AUTO_GEOLOCATED"|"VERIFIED";longitude:number;latitude:number}|null>(null);
  const [cadastralPickerOpen,setCadastralPickerOpen]=useState(false);const [cadastralImport,setCadastralImport]=useState<CadastralFeatureInfo|null>(null);const [sheet,setSheet]=useState(prefill?.sheet??"");const [parcel,setParcel]=useState(prefill?.parcel??"");
  const [subjectMode,setSubjectMode]=useState<"new"|"existing">("new");const [subjectType,setSubjectType]=useState<SubjectType>(prefill?.subjectType??"PRIVATO");const [existingSubjectId,setExistingSubjectId]=useState("");const [taxCode,setTaxCode]=useState(prefill?.taxCode??"");const [vatNumber,setVatNumber]=useState("");const [subjectQuery,setSubjectQuery]=useState("");const [availableSubjects,setAvailableSubjects]=useState<Subject[]>(embeddedSubjects);const [subjectSearchState,setSubjectSearchState]=useState<"idle"|"loading"|"error">("idle");
  const allowedStreets=useMemo(()=>streets.filter(street=>zones.find(zone=>zone.id===zoneId)?.streetIds.includes(street.id)),[streets,zoneId,zones]);
  const allowedCivics=useMemo(()=>civics.filter(civic=>civic.streetId===streetId),[civics,streetId]);const selectedCivic=civics.find(civic=>civic.id===civicId);const allowedComplexes=complexes.filter(complex=>complex.civicIds.includes(civicId));
  const locationStatus=locationOverride?.status??selectedCivic?.geocodingStatus??"NOT_GEOLOCATED";const selectedStreet=streets.find(street=>street.id===streetId);const selectedZone=zones.find(zone=>zone.id===zoneId);const locationAddress=selectedCivic&&selectedStreet?`${selectedStreet.name}, ${selectedCivic.number}${selectedCivic.extension?`/${selectedCivic.extension}`:""}, ${selectedZone?.municipality??selectedStreet.municipality}, Italia`:"";
  const matchingSubject=availableSubjects.find(subject=>(normalizeIdentifier(taxCode)&&normalizeIdentifier(subject.taxCode??"")===normalizeIdentifier(taxCode))||(normalizeIdentifier(vatNumber)&&normalizeIdentifier(subject.vatNumber??"")===normalizeIdentifier(vatNumber)));
  const selectExistingSubject=(subjectId:string)=>{setExistingSubjectId(subjectId);setSubjectMode("existing")};
  const clearCadastralImport=()=>{if(cadastralImport){setCadastralImport(null);setSheet("");setParcel("")}};
  async function searchSubjects(query:string){const needle=query.trim();if(needle.length<2)return;const embedded=embeddedSubjects.filter(subject=>[subject.firstName,subject.lastName,subject.companyName,subject.taxCode,subject.vatNumber].some(value=>value?.toLocaleLowerCase("it").includes(needle.toLocaleLowerCase("it"))));if(embedded.length){setAvailableSubjects(embedded);setSubjectSearchState("idle");return}setSubjectSearchState("loading");try{const response=await fetch(`/api/census/subjects?q=${encodeURIComponent(needle)}`);if(!response.ok)throw new Error();const parsed=subjectSearchResponseSchema.parse(await response.json());setAvailableSubjects(parsed.subjects);setSubjectSearchState("idle")}catch{setSubjectSearchState("error")}}

  return <form className="record-form" action={action}><input type="hidden" name="subjectType" value={subjectType}/>
    {state.error&&<div className="error-banner" role="alert"><AlertTriangle/>{state.error}</div>}
    <div className="form-grid">
      <section className="form-section"><div className="section-title"><span>01</span><div><h2>Indirizzo e immobile</h2><p>Via e civico devono essere già censiti nel territorio</p></div></div><div className="fields-grid">
        <label>Zona di censimento *<select name="zoneId" required value={zoneId} onChange={event=>{clearCadastralImport();setZoneId(event.target.value);setStreetId("");setCivicId("")}}><option value="">Seleziona…</option>{zones.map(zone=><option value={zone.id} key={zone.id}>{zone.name}</option>)}</select></label>
        <label>Via *<select name="streetId" required value={streetId} onChange={event=>{clearCadastralImport();setStreetId(event.target.value);setCivicId("")}} disabled={!zoneId}><option value="">Seleziona…</option>{allowedStreets.map(street=><option value={street.id} key={street.id}>{street.name}</option>)}</select></label>
        <label>Civico *<select name="civicId" required value={civicId} onChange={event=>{clearCadastralImport();setCivicId(event.target.value)}} disabled={!streetId}><option value="">Seleziona…</option>{allowedCivics.map(civic=><option value={civic.id} key={civic.id}>{civic.number}{civic.extension?`/${civic.extension}`:""}</option>)}</select></label>
        <label>Estensione<input value={selectedCivic?.extension??""} readOnly aria-describedby="extension-help"/><small id="extension-help">Definita separatamente nel civico</small></label>
        {selectedCivic&&<div className={`location-summary ${locationStatus.toLocaleLowerCase()}`}><strong>Posizione geografica</strong><span>{locationStatus==="VERIFIED"?"Posizione geografica verificata":locationStatus==="AUTO_GEOLOCATED"?"Posizione individuata automaticamente, da verificare":"Posizione non verificata"}</span><button type="button" className="button secondary" onClick={()=>setLocationPickerOpen(true)}>{locationStatus==="VERIFIED"?"Correggi sulla mappa":"Individua sulla mappa"}</button></div>}
        <label>Complesso<select name="complexId" disabled={!civicId} defaultValue={prefill?.complexId??""}><option value="">Nessuno</option>{allowedComplexes.map(complex=><option value={complex.id} key={complex.id}>{complex.name}</option>)}</select></label>
        <label>Scala<input name="staircase" placeholder="es. A"/></label><label>Interno<input name="unitIdentifier" placeholder="es. 4"/></label>
        <fieldset className="choice-field"><legend>Porzione censita</legend><label><input type="radio" name="buildingScope" value="Intero edificio" checked={buildingScope==="Intero edificio"} onChange={()=>setBuildingScope("Intero edificio")}/> Intero edificio</label><label><input type="radio" name="buildingScope" value="Parte di edificio" checked={buildingScope==="Parte di edificio"} onChange={()=>setBuildingScope("Parte di edificio")}/> Parte di edificio</label></fieldset>
        {buildingScope==="Intero edificio"?<label>Numero di livelli<input name="levels" type="number" min="1"/></label>:<><label>Piano *<select name="floorCode" required><option value="">Seleziona…</option>{floorCodes.map(floor=><option value={floor} key={floor}>{floor}</option>)}</select></label><label>Numero totale piani<input name="totalFloors" type="number" min="1" placeholder="es. 10"/></label><label className="checkbox"><input name="isTopFloor" type="checkbox"/> Ultimo piano</label></>}
        <label>Numero locali<input name="rooms" type="number" min="0" step="0.5"/></label><label>Superficie (m²)<input name="surface" type="number" min="0" step="0.01"/></label><label>Occupazione<select name="occupancy"><option value="">Non indicata</option>{occupancies.map(occupancy=><option value={occupancy} key={occupancy}>{occupancy}</option>)}</select></label><label className="checkbox"><input name="elevator" type="checkbox"/> Ascensore</label>
      </div></section>

      <section className="form-section"><div className="section-title"><span>02</span><div><h2>Dati del contatto</h2><p>Privato o azienda; l’anagrafica interna evita duplicazioni tra più contesti</p></div></div>
        <fieldset className="mode-switch"><legend>Anagrafica del contatto</legend><label><input type="radio" name="subjectMode" value="new" checked={subjectMode==="new"} onChange={()=>setSubjectMode("new")}/> Nuova anagrafica</label><label><input type="radio" name="subjectMode" value="existing" checked={subjectMode==="existing"} onChange={()=>setSubjectMode("existing")}/> Anagrafica già presente</label></fieldset>
        {subjectMode==="existing"?<div className="fields-grid"><label className="wide">Cerca anagrafica<input value={subjectQuery} onChange={event=>setSubjectQuery(event.target.value)} placeholder="Nome, ragione sociale, CF o P.IVA"/></label><button type="button" className="button secondary" disabled={subjectQuery.trim().length<2||subjectSearchState==="loading"} onClick={()=>void searchSubjects(subjectQuery)}>{subjectSearchState==="loading"?"Ricerca…":"Cerca"}</button><label className="wide">Contatto già presente *<select name="existingSubjectId" required value={existingSubjectId} onChange={event=>setExistingSubjectId(event.target.value)}><option value="">Seleziona…</option>{availableSubjects.map(subject=><option key={subject.id} value={subject.id}>{subjectDisplayName(subject)} · {subject.taxCode??subject.vatNumber??"senza identificativo"}</option>)}</select>{subjectSearchState==="error"&&<small className="form-error">Ricerca temporaneamente non disponibile.</small>}</label></div>:<><fieldset className="mode-switch"><legend>Tipo di contatto</legend><label><input type="radio" name="subjectType" value="PRIVATO" checked={subjectType==="PRIVATO"} onChange={()=>setSubjectType("PRIVATO")}/> Privato</label><label><input type="radio" name="subjectType" value="AZIENDA" checked={subjectType==="AZIENDA"} onChange={()=>setSubjectType("AZIENDA")}/> Azienda</label></fieldset><div className="fields-grid">
          {subjectType==="PRIVATO"?<><label>Nome<input name="firstName" defaultValue={prefill?.firstName}/></label><label>Cognome *<input name="lastName" required defaultValue={prefill?.lastName}/></label><label>Codice fiscale<input name="taxCode" value={taxCode} onChange={event=>setTaxCode(event.target.value)} onBlur={()=>void searchSubjects(taxCode)}/></label><DatePickerField name="birthDate" label="Data di nascita"/></>:<><label className="wide">Ragione sociale *<input name="companyName" required defaultValue={prefill?.companyName}/></label><label>Partita IVA<input name="vatNumber" value={vatNumber} onChange={event=>setVatNumber(event.target.value)} onBlur={()=>void searchSubjects(vatNumber)}/></label><label>Codice fiscale azienda<input name="taxCode" value={taxCode} onChange={event=>setTaxCode(event.target.value)} onBlur={()=>void searchSubjects(taxCode)}/></label></>}
          <label>Telefono<input name="phone" type="tel"/></label><label>E-mail<input name="email" type="email"/></label><label className="wide">Note soggetto<textarea name="notes" rows={3}/></label>
        </div>{matchingSubject&&<div className="database-notice"><Link2/><span>Questo soggetto è già presente. Vuoi collegarlo anche a questo immobile/civico? <strong>{subjectDisplayName(matchingSubject)}</strong></span><button type="button" className="button secondary" onClick={()=>selectExistingSubject(matchingSubject.id)}>Usa anagrafica esistente</button></div>}</>}
        <div className="fields-grid"><label>Ruolo nel contesto *<select name="relationshipRole" required defaultValue={prefill?.relationshipRole??""}><option value="">Seleziona…</option>{qualifications.map(qualification=><option value={qualification} key={qualification}>{qualification}</option>)}</select></label><label>Tipologia contatto<select name="contactType" value={contactType} onChange={event=>setContactType(event.target.value as ContactType)}>{["Generico","Informatore","Informazione","Notizia"].map(type=><option value={type} key={type}>{type}</option>)}</select></label><label>Tipo di incarico<select name="engagementType" value={engagementType} onChange={event=>setEngagementType(event.target.value as EngagementType)}>{engagementTypes.map(type=><option value={type} key={type}>{type}</option>)}</select></label>{(engagementType==="Incarico altre agenzie"||engagementType==="In esclusiva")&&<DatePickerField name="engagementExpiresOn" label="Scadenza incarico *" required help="Serve per ordinare le opportunità e intervenire prima della scadenza."/>}<label>Operatore responsabile<select name="responsibleOperatorId"><option value="">Non assegnato</option>{operators.map(operator=><option value={operator.id} key={operator.id}>{operator.name}</option>)}</select></label><label className="checkbox"><input name="inherited" type="checkbox"/> Immobile ereditato</label>{canShowAppraisal(contactType)&&<label className="checkbox appraisal"><input name="isAppraised" type="checkbox"/> Perizia Immobiliare <small>Flag manuale: Notizia non lo attiva automaticamente.</small></label>}</div>
      </section>

      <section className="form-section"><div className="section-title"><span>03</span><div><h2>Dati catastali dell’unità</h2><p>{prefill?"Precompilati da OpenAPI Catasto; verifica prima del salvataggio":"Dato operativo, non fonte catastale definitiva"}</p></div></div><div className={`cadastral-import-callout ${cadastralImport?"imported":""}`}><Layers/><div><strong>{cadastralImport?"Foglio e particella importati":"Importa dalla cartografia catastale gratuita"}</strong><span>{cadastralImport?`${cadastralImport.municipalityName??cadastralImport.municipalityCode} · foglio ${cadastralImport.sheet}, particella ${cadastralImport.parcel}`:"Seleziona prima il civico, poi clicca la particella arancione nel GeoCensimento."}</span></div><button type="button" className="button secondary" disabled={!selectedCivic} onClick={()=>setCadastralPickerOpen(true)}>{cadastralImport?"Cambia particella":"Apri GeoCensimento"}</button></div><div className="fields-grid four"><label>Foglio<input name="sheet" value={sheet} onChange={event=>{setSheet(event.target.value);setCadastralImport(null)}}/></label><label>Particella<input name="parcel" value={parcel} onChange={event=>{setParcel(event.target.value);setCadastralImport(null)}}/></label><label>Subalterno<input name="subaltern" defaultValue={prefill?.subaltern}/></label><label>Categoria catastale<select name="cadastralCategory" defaultValue={prefill?.cadastralCategory??""}><option value="">Non indicata</option>{cadastralCategories.map(([code,label])=><option key={code} value={code}>{code} · {label}</option>)}</select></label><label>Classe<input name="cadastralClass" defaultValue={prefill?.cadastralClass}/></label><label>Consistenza / vani<input name="cadastralConsistency" defaultValue={prefill?.cadastralConsistency}/></label><label>Rendita catastale<input name="cadastralIncome" defaultValue={prefill?.cadastralIncome}/></label><label>Zona censuaria<input name="cadastralCensusZone" defaultValue={prefill?.cadastralCensusZone}/></label><label>Partita<input name="cadastralRegistryLot" defaultValue={prefill?.cadastralRegistryLot}/></label><label className="wide">Indirizzo catastale<input name="cadastralAddress" defaultValue={prefill?.cadastralAddress}/></label></div></section><section className="form-section"><div className="section-title"><span>04</span><div><h2>Foto del contatto</h2><p>Facoltativa, privata e visibile nel popup della mappa dopo il salvataggio.</p></div></div><label>Carica foto<input name="contactPhoto" type="file" accept="image/jpeg,image/png,image/webp"/></label></section>
    </div>
    <div className="form-footer"><span><Database size={16}/>{databaseMode?"Salvataggio nel database Supabase LAB":"Fallback demo in sola lettura"}</span><SubmitButton databaseMode={databaseMode}/></div>
    {locationPickerOpen&&selectedCivic&&<CivicLocationPicker civic={{...selectedCivic,...(locationOverride?{geocodingStatus:locationOverride.status,location:{longitude:locationOverride.longitude,latitude:locationOverride.latitude}}:{})}} address={locationAddress} databaseMode={databaseMode} onClose={()=>setLocationPickerOpen(false)} onSaved={(status,longitude,latitude)=>setLocationOverride({status,longitude,latitude})}/>} 
    {cadastralPickerOpen&&selectedCivic&&<CadastralPicker civic={{...selectedCivic,...(locationOverride?{geocodingStatus:locationOverride.status,location:{longitude:locationOverride.longitude,latitude:locationOverride.latitude}}:{})}} address={locationAddress} onClose={()=>setCadastralPickerOpen(false)} onSaved={feature=>{setCadastralImport(feature);setSheet(feature.sheet);setParcel(feature.parcel)}}/>}
  </form>;
}
