"use server";

import{revalidatePath}from"next/cache";import{redirect}from"next/navigation";import{createClient,hasSupabaseEnvironment}from"@/lib/supabase/server";import{contactUpdateSchema}from"./schemas";import{uploadContactPhoto}from"@/services/contact-photo-data";
export type ContactEditState={error?:string};
const value=(data:FormData,key:string)=>String(data.get(key)??"").trim();
export async function updateContactAction(_state:ContactEditState,data:FormData):Promise<ContactEditState>{
  if(!hasSupabaseEnvironment())return{error:"Database LAB non configurato"};
  const parsed=contactUpdateSchema.safeParse({recordId:value(data,"recordId"),subjectId:value(data,"subjectId"),subjectType:value(data,"subjectType"),firstName:value(data,"firstName"),lastName:value(data,"lastName"),companyName:value(data,"companyName"),taxCode:value(data,"taxCode"),vatNumber:value(data,"vatNumber"),phone:value(data,"phone"),email:value(data,"email"),birthDate:value(data,"birthDate"),notes:value(data,"notes"),zoneId:value(data,"zoneId"),streetId:value(data,"streetId"),civicId:value(data,"civicId"),complexId:value(data,"complexId"),buildingScope:value(data,"buildingScope"),levels:value(data,"levels"),staircase:value(data,"staircase"),unitIdentifier:value(data,"unitIdentifier"),floorCode:value(data,"floorCode"),totalFloors:value(data,"totalFloors"),isTopFloor:data.get("isTopFloor")==="on",rooms:value(data,"rooms"),surface:value(data,"surface"),occupancy:value(data,"occupancy"),elevator:data.get("elevator")==="on",contactType:value(data,"contactType"),relationshipRole:value(data,"relationshipRole"),responsibleOperatorId:value(data,"responsibleOperatorId"),inherited:data.get("inherited")==="on",isAppraised:data.get("isAppraised")==="on",sheet:value(data,"sheet"),parcel:value(data,"parcel"),subaltern:value(data,"subaltern"),cadastralCategory:value(data,"cadastralCategory")});
  if(!parsed.success)return{error:parsed.error.issues[0]?.message??"Dati non validi"};
  const{recordId,...payload}=parsed.data;const db=await createClient();const{error}=await db.rpc("update_census_contact_lab",{p_record_id:recordId,p_contact:payload});if(error)return{error:error.message};const labels=await db.from("census_records").update({staircase:payload.staircase||null,unit_identifier:payload.unitIdentifier||null,cadastral_class:value(data,"cadastralClass")||null,cadastral_consistency:value(data,"cadastralConsistency")||null,cadastral_income:value(data,"cadastralIncome")||null,cadastral_census_zone:value(data,"cadastralCensusZone")||null,cadastral_registry_lot:value(data,"cadastralRegistryLot")||null,cadastral_address:value(data,"cadastralAddress")||null}).eq("id",recordId);if(labels.error)return{error:labels.error.message};const photo=data.get("contactPhoto");if(photo instanceof File&&photo.size>0)await uploadContactPhoto(recordId,photo);
  revalidatePath(`/censimento/contatti/${recordId}`);revalidatePath("/censimento/contatti");revalidatePath("/geocensimento");redirect(`/censimento/contatti/${recordId}?updated=1`);
}
