"use client";
import Link from "next/link";
import { ChevronDown, ChevronUp, Filter, RotateCcw, Search, SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";
import type { CensusRecord, CensusZone, Complex, Operator, Street } from "@/domain/census";
import { latestInterview, nextRecall } from "@/domain/census";
import { filterCensusRecords, type CensusFilters } from "./filters";

type Props = { records: CensusRecord[]; zones: CensusZone[]; streets: Street[]; complexes: Complex[]; operators: Operator[]; fixedZoneId?: string; fixedStreetId?: string };
export function ContactsTable({ records, zones, streets, complexes, operators, fixedZoneId, fixedStreetId }: Props) {
  const [filters, setFilters] = useState<CensusFilters>({ zoneId: fixedZoneId, streetId: fixedStreetId }); const [advanced, setAdvanced] = useState(false);
  const [sort, setSort] = useState<"name" | "created">("name"); const visible = useMemo(() => filterCensusRecords(records, filters).sort((a,b) => sort === "name" ? a.lastName.localeCompare(b.lastName) : b.createdAt.localeCompare(a.createdAt)), [records, filters, sort]);
  const update = (key: keyof CensusFilters, value: string) => setFilters((f) => ({ ...f, [key]: value || undefined }));
  const reset = () => setFilters({ zoneId: fixedZoneId, streetId: fixedStreetId });
  return <><section className="filter-panel"><div className="filter-primary"><label className="search-field"><Search size={18}/><input aria-label="Ricerca rapida" placeholder="Cerca nome, via o civico…" value={filters.query ?? ""} onChange={(e) => update("query", e.target.value)}/></label>{!fixedZoneId && <label>Zona<select value={filters.zoneId ?? ""} onChange={(e) => update("zoneId", e.target.value)}><option value="">Tutte</option>{zones.map((z) => <option key={z.id} value={z.id}>{z.name}</option>)}</select></label>}{!fixedStreetId && <label>Via<select value={filters.streetId ?? ""} onChange={(e) => update("streetId", e.target.value)}><option value="">Tutte</option>{streets.filter((s) => !filters.zoneId || zones.find((z) => z.id === filters.zoneId)?.streetIds.includes(s.id)).map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<button className="button secondary" onClick={() => setAdvanced(!advanced)}><SlidersHorizontal size={17}/> Altri filtri {advanced ? <ChevronUp size={16}/> : <ChevronDown size={16}/>}</button></div>
    {advanced && <div className="advanced-filters"><fieldset><legend>Contatto</legend><label>Cognome<input value={filters.lastName ?? ""} onChange={(e) => update("lastName", e.target.value)}/></label><label>Nome<input value={filters.firstName ?? ""} onChange={(e) => update("firstName", e.target.value)}/></label><label>Tipologia<select value={filters.contactType ?? ""} onChange={(e) => update("contactType", e.target.value)}><option value="">Tutte</option>{["Generico","Informatore","Informazione","Notizia"].map(v=><option key={v}>{v}</option>)}</select></label></fieldset><fieldset><legend>Immobile</legend><label>Complesso<select value={filters.complexId ?? ""} onChange={(e) => update("complexId", e.target.value)}><option value="">Tutti</option>{complexes.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Piano<input value={filters.floor ?? ""} onChange={(e) => update("floor", e.target.value)}/></label><label>Ascensore<select value={filters.elevator ?? ""} onChange={(e) => update("elevator",e.target.value)}><option value="">Tutti</option><option value="true">Sì</option><option value="false">No</option></select></label></fieldset><fieldset><legend>Catasto</legend><label>Foglio<input value={filters.sheet ?? ""} onChange={(e) => update("sheet", e.target.value)}/></label><label>Particella<input value={filters.parcel ?? ""} onChange={(e) => update("parcel", e.target.value)}/></label><label>Subalterno<input value={filters.subaltern ?? ""} onChange={(e) => update("subaltern", e.target.value)}/></label></fieldset><fieldset><legend>Gestione e stato</legend><label>Responsabile<select value={filters.operatorId ?? ""} onChange={(e) => update("operatorId",e.target.value)}><option value="">Tutti</option>{operators.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></label><label>Ereditato<select value={filters.inherited ?? ""} onChange={(e) => update("inherited",e.target.value)}><option value="">Tutti</option><option value="true">Sì</option><option value="false">No</option></select></label><label>Perizia<select value={filters.appraised ?? ""} onChange={(e) => update("appraised",e.target.value)}><option value="">Tutte</option><option value="true">Sì</option><option value="false">No</option></select></label></fieldset></div>}
    <div className="filter-actions"><span><Filter size={15}/>{visible.length} risultati</span><button className="text-button" onClick={reset}><RotateCcw size={15}/> Reimposta filtri</button></div></section>
    <section className="table-panel"><div className="table-toolbar"><strong>Contatti censimento</strong><label>Ordina per <select value={sort} onChange={(e) => setSort(e.target.value as "name"|"created")}><option value="name">Cognome</option><option value="created">Inserimento</option></select></label></div><div className="table-scroll"><table><thead><tr><th>Contatto</th><th>Tipologia</th><th>Zona / Indirizzo</th><th>Piano</th><th>Ultima intervista</th><th>Ricontatto</th><th>Complesso</th><th>Ereditato</th><th>Azioni</th></tr></thead><tbody>{visible.map((r) => { const latest = latestInterview(r); return <tr key={r.id}><td><strong>{r.lastName} {r.firstName}</strong><small>{r.phone ?? "—"}</small></td><td><span className={`badge ${r.contactType === "Notizia" ? "news" : ""}`}>{r.contactType}</span>{r.isAppraised && <small>Periziato</small>}</td><td><strong>{r.zoneName}</strong><small>{r.streetName}, {r.civicNumber}{r.civicExtension ? `/${r.civicExtension}` : ""}</small></td><td>{r.floorLabel ?? "—"}</td><td>{latest?.interviewDate ?? "—"}<small>{latest?.operatorName}</small></td><td>{nextRecall(r) ?? "—"}</td><td>{r.complexName ?? "—"}</td><td>{r.inherited ? "Sì" : "No"}</td><td><Link className="row-action" href={`/censimento/contatti/${r.id}`}>Apri</Link></td></tr>})}</tbody></table></div></section></>;
}
