"use client";

import{useActionState,useMemo,useState}from"react";import{AlertTriangle,Save}from"lucide-react";import Link from"next/link";import{contactTypes,floorCodes,occupancies,qualifications,type BuildingScope,type CensusRecord,type CensusZone,type Civic,type Complex,type Operator,type Street,type Subject}from"@/domain/census";import{updateContactAction}from"./contact-edit-actions";import{CivicLocationPicker}from"./civic-location-picker";

export function ContactEditForm({record,subject,zones,streets,civics,complexes,operators,databaseMode}:{record:CensusRecord;subject:Subject;zones:CensusZone[];streets:Street[];civics:Civic[];complexes:Complex[];operators:Operator[];databaseMode:boolean}){
  const[state,action,pending]=useActionState(updateContactAction,{});const[zoneId,setZoneId]=useState(record.zoneId);const[streetId,setStreetId]=useState(record.streetId);const[civicId,setCivicId]=useState(record.civicId);const[complexId,setComplexId]=useState(record.complexId??"");const[scope,setScope]=useState<BuildingScope>(record.buildingScope);const[type,setType]=useState(record.contactType);const[locationPickerOpen,setLocationPickerOpen]=useState(false);const[locationOverride,setLocationOverride]=useState<{status:"AUTO_GEOLOCATED"|"VERIFIED";longitude:number;latitude:number}|null>(null);
  const allowedStreets=useMemo(()=>streets.filter(street=>zones.find(zone=>zone.id===zoneId)?.streetIds.includes(street.id)),[streets,zones,zoneId]);const allowedCivics=civics.filter(civic=>civic.streetId===streetId);const allowedComplexes=complexes.filter(complex=>complex.civicIds.includes(civicId));const primary=record.subjectLinks.find(link=>link.isPrimary)??record.subjectLinks[0];const selectedCivic=civics.find(civic=>civic.id===civicId);const selectedStreet=streets.find(street=>street.id===streetId);const selectedZone=zones.find(zone=>zone.id===zoneId);const locationStatus=locationOverride?.status??selectedCivic?.geocodingStatus??"NOT_GEOLOCATED";const locationAddress=selectedCivic&&selectedStreet?`${selectedStreet.name}, ${selectedCivic.number}${selectedCivic.extension?`/${selectedCivic.extension}`:""}, ${selectedZone?.municipality??selectedStreet.municipality}, Italia`:"";
  return <form className="record-form" action={action}><input type="hidden" name="recordId" value={record.id}/><input type="hidden" name="subjectId" value={subject.id}/><input type="hidden" name="subjectType" value={subject.subjectType}/>{state.error&&<div className="error-banner" role="alert"><AlertTriangle/>{state.error}</div>}<div className="form-grid">
    <section className="form-section"><div className="section-title"><span>01</span><div><h2>Contesto immobiliare</h2><p>Zona, indirizzo e caratteristiche del contatto censito</p></div></div><div className="fields-grid">
      <label>Zona di censimento *<select name="zoneId" required value={zoneId} onChange={event=>{setZoneId(event.target.value);setStreetId("");setCivicId("");setComplexId("")}}>{zones.map(zone=><option key={zone.id} value={zone.id}>{zone.name}</option>)}</select></label>
      <label>Via *<select name="streetId" required value={streetId} onChange={event=>{setStreetId(event.target.value);setCivicId("");setComplexId("")}}>{allowedStreets.map(street=><option key={street.id} value={street.id}>{street.name}</option>)}</select></label>
      <label>Civico *<select name="civicId" required value={civicId} onChange={event=>{setCivicId(event.target.value);setComplexId("")}}>{allowedCivics.map(civic=><option key={civic.id} value={civic.id}>{civic.number}{civic.extension?`/${civic.extension}`:""}</option>)}</select></label>
      {selectedCivic&&<div className={`location-summary ${locationStatus.toLocaleLowerCase()}`}><strong>Posizione geografica</strong><span>{locationStatus==="VERIFIED"?"Posizione geografica verificata":locationStatus==="AUTO_GEOLOCATED"?"Posizione individuata automaticamente, da verificare":"Posizione non verificata"}</span><button type="button" className="button secondary" onClick={()=>setLocationPickerOpen(true)}>{locationStatus==="VERIFIED"?"Correggi sulla mappa":"Individua sulla mappa"}</button></div>}
      <label>Complesso<select name="complexId" value={complexId} onChange={event=>setComplexId(event.target.value)}><option value="">Nessuno</option>{allowedComplexes.map(complex=><option key={complex.id} value={complex.id}>{complex.name}</option>)}</select></label>
      <fieldset className="choice-field"><legend>Porzione censita</legend><label><input type="radio" name="buildingScope" value="Intero edificio" checked={scope==="Intero edificio"} onChange={()=>setScope("Intero edificio")}/> Intero edificio</label><label><input type="radio" name="buildingScope" value="Parte di edificio" checked={scope==="Parte di edificio"} onChange={()=>setScope("Parte di edificio")}/> Parte di edificio</label></fieldset>
      {scope==="Intero edificio"?<label>Numero livelli<input name="levels" type="number" min="1" defaultValue={record.levels}/></label>:<><label>Piano *<select name="floorCode" required defaultValue={record.floorCode??""}><option value="">Seleziona…</option>{floorCodes.map(floor=><option key={floor}>{floor}</option>)}</select></label><label>Numero totale piani<input name="totalFloors" type="number" min="1" defaultValue={record.totalFloors}/></label><label className="checkbox"><input name="isTopFloor" type="checkbox" defaultChecked={record.isTopFloor}/> Ultimo piano</label></>}
      <label>Numero locali<input name="rooms" type="number" min="0" step="0.5" defaultValue={record.rooms}/></label><label>Superficie (m²)<input name="surface" type="number" min="0" step="0.01" defaultValue={record.surface}/></label><label>Occupazione<select name="occupancy" defaultValue={record.occupancy??""}><option value="">Non indicata</option>{occupancies.map(value=><option key={value}>{value}</option>)}</select></label><label className="checkbox"><input name="elevator" type="checkbox" defaultChecked={record.elevator}/> Ascensore</label>
    </div></section>
    <section className="form-section"><div className="section-title"><span>02</span><div><h2>Anagrafica e gestione</h2><p>Modifica il soggetto principale e i dati operativi del contesto</p></div></div><div className="fields-grid">
      {subject.subjectType==="PRIVATO"?<><label>Nome<input name="firstName" defaultValue={subject.firstName}/></label><label>Cognome *<input name="lastName" required defaultValue={subject.lastName}/></label><label>Codice fiscale<input name="taxCode" defaultValue={subject.taxCode}/></label><label>Data di nascita<input name="birthDate" type="date" defaultValue={subject.birthDate}/></label></>:<><label className="wide">Ragione sociale *<input name="companyName" required defaultValue={subject.companyName}/></label><label>Partita IVA<input name="vatNumber" defaultValue={subject.vatNumber}/></label><label>Codice fiscale<input name="taxCode" defaultValue={subject.taxCode}/></label></>}
      <label>Telefono<input name="phone" defaultValue={subject.phone}/></label><label>E-mail<input name="email" type="email" defaultValue={subject.email}/></label><label className="wide">Note<textarea name="notes" rows={3} defaultValue={subject.notes}/></label>
      <label>Ruolo *<select name="relationshipRole" required defaultValue={primary?.role??""}>{qualifications.map(role=><option key={role}>{role}</option>)}</select></label><label>Tipologia contatto<select name="contactType" value={type} onChange={event=>setType(event.target.value as typeof type)}>{contactTypes.map(value=><option key={value}>{value}</option>)}</select></label><label>Operatore responsabile<select name="responsibleOperatorId" defaultValue={record.responsibleOperatorId??""}><option value="">Non assegnato</option>{operators.map(operator=><option key={operator.id} value={operator.id}>{operator.name}</option>)}</select></label><label className="checkbox"><input name="inherited" type="checkbox" defaultChecked={record.inherited}/> Immobile ereditato</label>{type==="Notizia"&&<label className="checkbox appraisal"><input name="isAppraised" type="checkbox" defaultChecked={record.isAppraised}/> Perizia immobiliare</label>}
    </div></section>
    <section className="form-section"><div className="section-title"><span>03</span><div><h2>Dati catastali manuali</h2><p>Restano modificabili indipendentemente dall’associazione cartografica</p></div></div><div className="fields-grid four"><label>Foglio<input name="sheet" defaultValue={record.sheet}/></label><label>Particella<input name="parcel" defaultValue={record.parcel}/></label><label>Subalterno<input name="subaltern" defaultValue={record.subaltern}/></label><label>Categoria catastale<input name="cadastralCategory" defaultValue={record.cadastralCategory}/></label></div></section>
  </div><div className="form-footer"><Link className="button secondary" href={`/censimento/contatti/${record.id}`}>Annulla</Link><button className="button primary" disabled={pending||!databaseMode}><Save size={17}/>{pending?"Salvataggio…":"Salva modifiche"}</button></div>{locationPickerOpen&&selectedCivic&&<CivicLocationPicker civic={{...selectedCivic,...(locationOverride?{geocodingStatus:locationOverride.status,location:{longitude:locationOverride.longitude,latitude:locationOverride.latitude}}:{})}} address={locationAddress} databaseMode={databaseMode} onClose={()=>setLocationPickerOpen(false)} onSaved={(status,longitude,latitude)=>setLocationOverride({status,longitude,latitude})}/>}</form>
}
