"use client";
import { useMemo, useState } from "react";
import { Check, FlaskConical, Save } from "lucide-react";
import { civics, complexes, operators, streets, zones } from "@/lib/demo-data";
import { canShowAppraisal, type ContactType } from "@/domain/census";

export function ContactForm() {
  const [zoneId,setZone]=useState(""); const [streetId,setStreet]=useState(""); const [contactType,setType]=useState<ContactType>("Generico"); const [saved,setSaved]=useState(false);
  const allowedStreets=useMemo(()=>streets.filter(s=>zones.find(z=>z.id===zoneId)?.streetIds.includes(s.id)),[zoneId]); const allowedCivics=civics.filter(c=>c.streetId===streetId);
  return <form className="record-form" onSubmit={(e)=>{e.preventDefault();setSaved(true);window.scrollTo({top:0,behavior:"smooth"})}}>{saved&&<div className="success-banner"><Check/> Validazione completata. In demo LAB il record non viene persistito.</div>}<div className="form-grid"><section className="form-section"><div className="section-title"><span>01</span><div><h2>Indirizzo e immobile</h2><p>Localizzazione nel territorio di censimento</p></div></div><div className="fields-grid"><label>Zona di censimento *<select required value={zoneId} onChange={e=>{setZone(e.target.value);setStreet("")}}><option value="">Seleziona…</option>{zones.map(z=><option value={z.id} key={z.id}>{z.name}</option>)}</select></label><label>Via *<select required value={streetId} onChange={e=>setStreet(e.target.value)}><option value="">Seleziona…</option>{allowedStreets.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Civico *<select required><option value="">Seleziona…</option>{allowedCivics.map(c=><option value={c.id} key={c.id}>{c.number}{c.extension?`/${c.extension}`:""}</option>)}</select></label><label>Complesso<select><option value="">Nessuno</option>{complexes.filter(c=>!zoneId||c.zoneId===zoneId).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><fieldset className="choice-field"><legend>Porzione censita</legend><label><input type="radio" name="scope" defaultChecked/> Intero edificio</label><label><input type="radio" name="scope"/> Parte di edificio <span className="tbd-mini">TBD</span></label></fieldset><label>Numero di livelli<input type="number" min="1"/></label><label>Piano / posizione<input placeholder="es. 3° di 10"/></label><label>Numero locali<input type="number" min="0"/></label><label>Superficie (m²)<input type="number" min="0"/></label><label>Occupazione<select><option value="">Non indicata</option><option>Libero</option><option>Occupato</option></select></label><label className="checkbox"><input type="checkbox"/> Ascensore</label></div></section>
  <section className="form-section"><div className="section-title"><span>02</span><div><h2>Anagrafica</h2><p>Persona e qualificazione del contatto</p></div></div><div className="fields-grid"><label>Nome<input name="firstName"/></label><label>Cognome *<input name="lastName" required/></label><label>Telefono<input type="tel"/></label><label>E-mail<input type="email"/></label><label>Codice fiscale<input/></label><label>Tipologia contatto<select value={contactType} onChange={e=>setType(e.target.value as ContactType)}>{["Generico","Informatore","Informazione","Notizia"].map(v=><option key={v}>{v}</option>)}</select></label><label>Qualifica<input/></label><label>Data di nascita<input type="date"/></label><label>Operatore responsabile<select><option value="">Non assegnato</option>{operators.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></label><label className="checkbox"><input type="checkbox"/> Immobile ereditato</label>{canShowAppraisal(contactType)&&<label className="checkbox appraisal"><input type="checkbox"/> Perizia Immobiliare <small>Selezione manuale: Notizia non la attiva automaticamente.</small></label>}<label className="wide">Annotazioni anagrafiche<textarea rows={3}/></label></div></section>
  <section className="form-section"><div className="section-title"><span>03</span><div><h2>Dati catastali manuali</h2><p>Dato operativo, non fonte catastale definitiva</p></div></div><div className="fields-grid four"><label>Foglio<input/></label><label>Particella<input/></label><label>Subalterno<input/></label><label>Categoria catastale<input placeholder="es. A/2"/></label></div></section>
  <section className="form-section"><div className="section-title"><span>04</span><div><h2>Prima intervista</h2><p>Opzionale; sarà aggiunta allo storico</p></div></div><div className="fields-grid"><label>Effettuata da<select><option value="">Seleziona…</option>{operators.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></label><label>Data intervista<input type="date"/></label><label>Data ricontatto<input type="date"/></label><label>Risposta<input/></label><label>Motivo<input/></label><label>Esito<input/></label></div></section></div><div className="form-footer"><span><FlaskConical size={16}/> Salvataggio simulato in modalità demo</span><button className="button primary" type="submit"><Save size={17}/> Salva contatto</button></div></form>;
}
