"use client";

import { useActionState, useState } from "react";
import { AlertTriangle, Link2 } from "lucide-react";
import { z } from "zod";
import { qualifications, subjectDisplayName, type Subject } from "@/domain/census";
import { linkSubjectAction } from "./subject-actions";

export function SubjectLinkForm({recordId,subjects,databaseMode}:{recordId:string;subjects:Subject[];databaseMode:boolean}){
  const [state,action,pending]=useActionState(linkSubjectAction,{});const [query,setQuery]=useState("");const [results,setResults]=useState<Subject[]>([]);const [searching,setSearching]=useState(false);const schema=z.object({subjects:z.array(z.object({id:z.string(),subjectType:z.enum(["PRIVATO","AZIENDA"]),firstName:z.string().optional(),lastName:z.string().optional(),companyName:z.string().optional(),taxCode:z.string().optional(),vatNumber:z.string().optional(),phone:z.string().optional(),email:z.string().optional(),birthDate:z.string().optional(),notes:z.string().optional()}))});
  async function search(){setSearching(true);try{const response=await fetch(`/api/census/subjects?q=${encodeURIComponent(query.trim())}`);const parsed=schema.parse(await response.json());setResults(parsed.subjects.filter(subject=>!subjects.some(linked=>linked.id===subject.id)))}catch{setResults([])}finally{setSearching(false)}}
  return <form className="panel record-form" action={action}><input type="hidden" name="recordId" value={recordId}/><div className="panel-heading"><div><p className="eyebrow">Più persone sullo stesso contesto</p><h2>Aggiungi proprietario, comproprietario o inquilino</h2></div><Link2/></div>{state.error&&<div className="error-banner" role="alert"><AlertTriangle/>{state.error}</div>}{state.success&&<div className="success-banner">{state.success}</div>}<div className="fields-grid"><label>Cerca anagrafica<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Nome, CF o P.IVA"/></label><button type="button" className="button secondary" disabled={query.trim().length<2||searching} onClick={()=>void search()}>{searching?"Ricerca…":"Cerca"}</button><label>Anagrafica già presente *<select name="subjectId" required><option value="">Seleziona…</option>{results.map(subject=><option value={subject.id} key={subject.id}>{subjectDisplayName(subject)}</option>)}</select></label><label>Ruolo *<select name="role" required><option value="">Seleziona…</option>{qualifications.map(role=><option key={role}>{role}</option>)}</select></label></div><div className="button-row"><button className="button primary" disabled={pending||!databaseMode}>{pending?"Collegamento…":"Aggiungi al contatto"}</button></div></form>;
}
