"use client";

import { useActionState, useState } from "react";
import { AlertTriangle, Link2 } from "lucide-react";
import { z } from "zod";
import { qualifications, subjectDisplayName, type Subject, type SubjectSearchResult } from "@/domain/census";
import { linkSubjectAction } from "./subject-actions";

export function SubjectLinkForm({recordId,subjects,databaseMode}:{recordId:string;subjects:Subject[];databaseMode:boolean}){
  const [state,action,pending]=useActionState(linkSubjectAction,{});const [query,setQuery]=useState("");const [results,setResults]=useState<SubjectSearchResult[]>([]);const [searchState,setSearchState]=useState<"idle"|"loading"|"empty"|"error"|"success">("idle");const schema=z.object({subjects:z.array(z.object({id:z.string(),subjectType:z.enum(["PRIVATO","AZIENDA"]),firstName:z.string().optional(),lastName:z.string().optional(),companyName:z.string().optional(),taxCode:z.string().optional(),vatNumber:z.string().optional(),phone:z.string().optional(),email:z.string().optional(),birthDate:z.string().optional(),notes:z.string().optional(),contextCount:z.number().int().nonnegative().default(0),contexts:z.array(z.object({recordId:z.string(),role:z.enum(["Proprietario","Comproprietario","Inquilino","Non specificato"]),address:z.string()})).default([])}))});
  async function search(){setSearchState("loading");try{const response=await fetch(`/api/census/subjects?q=${encodeURIComponent(query.trim())}`);if(!response.ok)throw new Error();const parsed=schema.parse(await response.json());const available=parsed.subjects.filter(subject=>!subjects.some(linked=>linked.id===subject.id));setResults(available);setSearchState(available.length?"success":"empty")}catch{setResults([]);setSearchState("error")}}
  return <form className="panel record-form" action={action}><input type="hidden" name="recordId" value={recordId}/><div className="panel-heading"><div><p className="eyebrow">Più persone sullo stesso contesto</p><h2>Aggiungi proprietario, comproprietario o inquilino</h2></div><Link2/></div>{state.error&&<div className="error-banner" role="alert"><AlertTriangle/>{state.error}</div>}{state.success&&<div className="success-banner">{state.success}</div>}<div className="fields-grid"><label>Cerca anagrafica<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Cognome e nome, CF, P.IVA o telefono"/></label><button type="button" className="button secondary" disabled={query.trim().length<2||searchState==="loading"} onClick={()=>void search()}>{searchState==="loading"?"Ricerca…":"Cerca"}</button><label>Anagrafica già presente *<select name="subjectId" required><option value="">Seleziona…</option>{results.map(subject=><option value={subject.id} key={subject.id}>{subjectDisplayName(subject)} · {subject.contextCount} immobili</option>)}</select></label><label>Ruolo *<select name="role" required><option value="">Seleziona…</option>{qualifications.map(role=><option key={role}>{role}</option>)}</select></label></div>{searchState==="empty"&&<p className="muted">Nessun’altra anagrafica trovata.</p>}{searchState==="error"&&<div className="error-banner compact" role="alert"><AlertTriangle/>Ricerca temporaneamente non disponibile.</div>}<div className="button-row"><button className="button primary" disabled={pending||!databaseMode}>{pending?"Collegamento…":"Aggiungi al contatto"}</button></div></form>;
}
