import { notFound } from "next/navigation";
import { PageHeader } from "@/components/ui";
import { ContactsTable } from "@/features/census/contacts-table";
import { civicLabel } from "@/domain/census";
import { loadCensusData } from "@/services/census-data";
import Link from "next/link";
import { ComplexPhotoManager } from "@/features/complex-photos/complex-photo-manager";
import { loadComplexPhotoData } from "@/services/complex-photo-data";
import { ComplexDeleteButton } from "@/features/complexes/complex-delete-button";
export default async function ComplexPage({params}:{params:Promise<{complexId:string}>}){const {complexId}=await params;const [{complexes,operators,records,streets,zones,operationalSettings,operationalToday},photoData]=await Promise.all([loadCensusData(["complexes","operators","records","streets","zones","operationalSettings"],{records:{complexId}}),loadComplexPhotoData(complexId)]);const complex=complexes.find(c=>c.id===complexId);if(!complex)notFound();const {civics:linked}=await loadCensusData(["civics"],{civicIds:complex.civicIds});const primary=linked.find(c=>c.id===complex.primaryAccessId);const other=linked.filter(c=>c.id!==complex.primaryAccessId);const address=(id:string)=>{const access=linked.find(c=>c.id===id);return access?`${streets.find(s=>s.id===access.streetId)?.name??"Via"} ${civicLabel(access)}`:"—"};const photoRevision=photoData.photos.map(photo=>`${photo.id}:${photo.processingStatus}`).concat(photoData.proposals.map(proposal=>`${proposal.id}:${proposal.status}`)).join("|");return <><PageHeader eyebrow="Censimento / Complessi" title={complex.name} description={zones.find(zone=>zone.id===complex.zoneId)?.name??"Zona non disponibile"} action={<div className="button-row"><Link className="button secondary" href={`/censimento/complessi/${complex.id}/modifica`}>Modifica complesso</Link><Link className="button secondary" href={`/geocensimento?zone=${complex.zoneId}&complex=true`}>Apri in GeoCensimento</Link><ComplexDeleteButton id={complex.id}/></div>}/><section className="panel complex-detail"><h2>Dati del complesso</h2><dl><div><dt>Indirizzo principale</dt><dd>{primary?address(primary.id):"Non indicato"}</dd></div><div><dt>Altri accessi</dt><dd>{other.length?other.map(item=>address(item.id)).join(" · "):"Nessuno"}</dd></div><div><dt>N° unità</dt><dd>{complex.units??"—"}</dd></div><div><dt>Foglio</dt><dd>{complex.sheet??"—"}</dd></div><div><dt>Particella</dt><dd>{complex.parcel??"—"}</dd></div><div><dt>Descrizione</dt><dd>{complex.description??"—"}</dd></div><div><dt>Contatti collegati</dt><dd>{records.length}</dd></div></dl></section><section className="complex-ocr-heading panel"><h2>Campanelli e interni</h2><p>Carica foto campanelli, avvia l’analisi e verifica le proposte prima di creare Contatti.</p><div className="complex-ocr-stats"><span>{photoData.photos.filter(photo=>photo.photoType==="DOORBELL").length} foto campanelli</span><span>{photoData.proposals.filter(proposal=>proposal.status==="DRAFT").length} proposte da verificare</span><span>{photoData.proposals.filter(proposal=>proposal.status==="CREATED").length} confermate</span></div></section><ComplexPhotoManager key={photoRevision} complexId={complexId} civics={linked} operators={operators} {...photoData}/><section className="complex-contacts"><h2>Contatti associati al complesso</h2><ContactsTable records={records} {...{zones,streets,complexes,operators,operationalSettings,operationalToday}}/></section></>}
