import { z } from "zod";
import type { CensusRepository } from "./census-repository";
import type { CensusRecord, CensusZone, Civic, Complex, Country, Municipality, Operator, Province, Region, Street, Subject } from "@/domain/census";
import { contactTypes, formatFloor, occupancies, qualifications } from "@/domain/census";
import { createClient } from "@/lib/supabase/server";

const row=z.record(z.string(),z.unknown()); const rows=z.array(row);
const text=(value:unknown)=>typeof value==="string"?value:undefined;
const object=(value:unknown)=>row.safeParse(value).success?value as Record<string,unknown>:undefined;
async function checked<T>(promise:PromiseLike<{data:unknown;error:{message:string}|null}>,map:(value:Record<string,unknown>)=>T):Promise<T[]>{const {data,error}=await promise;if(error)throw new Error(error.message);return rows.parse(data).map(map)}
async function checkedPaged<T>(page:(from:number,to:number)=>PromiseLike<{data:unknown;error:{message:string}|null}>,map:(value:Record<string,unknown>)=>T):Promise<T[]>{const result:T[]=[];const pageSize=1000;for(let from=0;;from+=pageSize){const current=await checked(page(from,from+pageSize-1),map);result.push(...current);if(current.length<pageSize)return result}}

function mapSubject(r:Record<string,unknown>):Subject{return {id:String(r.id),subjectType:r.subject_type==="AZIENDA"?"AZIENDA":"PRIVATO",firstName:text(r.first_name),lastName:text(r.last_name),companyName:text(r.company_name),taxCode:text(r.tax_code),vatNumber:text(r.vat_number),phone:text(r.phone),email:text(r.email),birthDate:text(r.birth_date),notes:text(r.notes)}}

export const supabaseCensusRepository:CensusRepository={
  async listCountries():Promise<Country[]>{const db=await createClient();return checked(db.from("countries").select("id,code,name").order("name"),r=>({id:String(r.id),code:String(r.code),name:String(r.name)}))},
  async listRegions():Promise<Region[]>{const db=await createClient();return checked(db.from("regions").select("id,country_id,name,istat_code").eq("is_active",true).order("name"),r=>({id:String(r.id),countryId:String(r.country_id),name:String(r.name),istatCode:text(r.istat_code)}))},
  async listProvinces():Promise<Province[]>{const db=await createClient();return checked(db.from("provinces").select("id,region_id,code,name,istat_code,territorial_unit_type").eq("is_active",true).order("name"),r=>({id:String(r.id),regionId:String(r.region_id),code:text(r.code),name:String(r.name),istatCode:text(r.istat_code),territorialUnitType:r.territorial_unit_type==null?undefined:Number(r.territorial_unit_type)}))},
  async listMunicipalities():Promise<Municipality[]>{const db=await createClient();return checkedPaged((from,to)=>db.from("municipalities").select("id,province_id,name,istat_code,cadastral_code").eq("is_active",true).order("name").order("istat_code").range(from,to),r=>({id:String(r.id),provinceId:String(r.province_id),name:String(r.name),istatCode:text(r.istat_code),cadastralCode:text(r.cadastral_code)}))},
  async listSubjects():Promise<Subject[]>{const db=await createClient();return checked(db.from("subjects").select("id,subject_type,first_name,last_name,company_name,tax_code,vat_number,phone,email,birth_date,notes").order("created_at"),mapSubject)},
  async getOperationalSettings(){const db=await createClient();const {data,error}=await db.from("census_operational_settings").select("stale_news_days").eq("id",1).single();if(error)throw new Error(error.message);const parsed=row.parse(data);return{staleNewsDays:z.number().int().positive().parse(parsed.stale_news_days)}},
  async listOperators():Promise<Operator[]>{const db=await createClient();return checked(db.from("operators").select("id,display_name"),r=>({id:String(r.id),name:String(r.display_name)}))},
  async listStreets():Promise<Street[]>{const db=await createClient();return checked(db.from("streets").select("id,municipality_id,name,municipalities(name)").order("name"),r=>({id:String(r.id),municipalityId:String(r.municipality_id),name:String(r.name),municipality:String(object(r.municipalities)?.name??"")}))},
  async listCivics():Promise<Civic[]>{const db=await createClient();return checked(db.from("civics").select("id,street_id,number,extension"),r=>({id:String(r.id),streetId:String(r.street_id),number:String(r.number),extension:text(r.extension)}))},
  async listZones():Promise<CensusZone[]>{const db=await createClient();const [zoneRows,links]=await Promise.all([checked(db.from("census_zones").select("id,name,municipality_id,municipalities(name),operators(id,display_name)"),r=>r),checked(db.from("census_zone_streets").select("census_zone_id,street_id"),r=>r)]);return zoneRows.map(r=>{const op=object(r.operators);return{id:String(r.id),name:String(r.name),municipalityId:String(r.municipality_id),municipality:String(object(r.municipalities)?.name??""),operator:{id:String(op?.id??""),name:String(op?.display_name??"Non assegnato")},streetIds:links.filter(l=>l.census_zone_id===r.id).map(l=>String(l.street_id))}})},
  async listComplexes():Promise<Complex[]>{const db=await createClient();const [complexRows,links]=await Promise.all([checked(db.from("complexes").select("id,name,census_zone_id,sheet,parcel,unit_count,description"),r=>r),checked(db.from("complex_civics").select("complex_id,civic_id"),r=>r)]);return complexRows.map(r=>({id:String(r.id),name:String(r.name),zoneId:String(r.census_zone_id),civicIds:links.filter(l=>l.complex_id===r.id).map(l=>String(l.civic_id)),sheet:text(r.sheet),parcel:text(r.parcel),units:typeof r.unit_count==="number"?r.unit_count:undefined,description:text(r.description)}))},
  async listRecords():Promise<CensusRecord[]>{
    const db=await createClient();
    const result=await checked(db.from("census_records").select("*,census_zones(name),streets(name),civics(number,extension),complexes(name),contact_types(label),operators(id,display_name),census_interviews(*,operators(display_name)),census_record_subjects(subject_id,role,is_primary,subjects(id,subject_type,first_name,last_name,company_name,tax_code,vat_number,phone,email,birth_date,notes))"),r=>r);
    return result.map(r=>{
      const zone=object(r.census_zones),street=object(r.streets),civic=object(r.civics),complex=object(r.complexes),ct=object(r.contact_types),op=object(r.operators);
      const rawLinks=Array.isArray(r.census_record_subjects)?r.census_record_subjects.map(value=>row.parse(value)):[];
      const subjectLinks=rawLinks.map(link=>({subjectId:String(link.subject_id),role:qualifications.find(value=>value===link.role)??"Non specificato" as const,isPrimary:Boolean(link.is_primary)}));
      const primaryLink=rawLinks.find(link=>Boolean(link.is_primary))??rawLinks[0]; const primarySubject=object(primaryLink?.subjects);
      const interviews=Array.isArray(r.census_interviews)?r.census_interviews.map(value=>row.parse(value)).map(interview=>({id:String(interview.id),recordId:String(interview.census_record_id),operatorId:String(interview.operator_id),operatorName:String(object(interview.operators)?.display_name??""),interviewDate:String(interview.interview_date),recallDate:text(interview.recall_date),response:text(interview.response),reason:text(interview.reason),outcome:text(interview.outcome)})):[];
      const contactType=contactTypes.find(value=>value===ct?.label)??"Generico";const floorCode=text(r.floor_code);const totalFloors=typeof r.total_floors==="number"?r.total_floors:undefined;const occupancy=occupancies.find(value=>value===r.occupancy);
      return {id:String(r.id),firstName:text(primarySubject?.first_name)??text(r.first_name),lastName:text(primarySubject?.last_name)??text(primarySubject?.company_name)??text(r.last_name)??"Soggetto",phone:text(primarySubject?.phone)??text(r.phone),email:text(primarySubject?.email)??text(r.email),taxCode:text(primarySubject?.tax_code)??text(r.tax_code),contactType,qualification:subjectLinks[0]?.role??text(r.qualification),inherited:Boolean(r.inherited),birthDate:text(primarySubject?.birth_date)??text(r.birth_date),responsibleOperatorId:text(r.responsible_operator_id),responsibleOperatorName:text(op?.display_name),notes:text(r.personal_notes),zoneId:String(r.census_zone_id),zoneName:String(zone?.name??""),streetId:String(r.street_id),streetName:String(street?.name??""),civicId:String(r.civic_id),civicNumber:String(civic?.number??""),civicExtension:text(civic?.extension),complexId:text(r.complex_id),complexName:text(complex?.name),buildingScope:r.building_scope==="Intero edificio"?"Intero edificio":"Parte di edificio",levels:typeof r.levels==="number"?r.levels:undefined,floorCode,totalFloors,isTopFloor:Boolean(r.is_top_floor),floorLabel:formatFloor(floorCode,totalFloors,Boolean(r.is_top_floor))??text(r.floor_label),rooms:typeof r.rooms==="number"?r.rooms:undefined,surface:typeof r.surface_sqm==="number"?r.surface_sqm:undefined,occupancy,elevator:typeof r.has_elevator==="boolean"?r.has_elevator:undefined,sheet:text(r.sheet),parcel:text(r.parcel),subaltern:text(r.subaltern),cadastralCategory:text(r.cadastral_category),isAppraised:Boolean(r.is_appraised),probableAssignment:typeof r.probable_assignment==="boolean"?r.probable_assignment:undefined,engagementType:text(r.engagement_type),createdAt:String(r.created_at),interviews,subjectLinks};
    });
  },
};
