import { z } from "zod";
import type { CensusRepository } from "./census-repository";
import type { CensusRecord, CensusZone, Civic, Complex, Country, Municipality, Operator, Province, Region, Street } from "@/domain/census";
import { contactTypes, formatFloor, occupancies } from "@/domain/census";
import { createClient } from "@/lib/supabase/server";

const row = z.record(z.string(), z.unknown());
const rows = z.array(row);
const text = (value: unknown) => typeof value === "string" ? value : undefined;
const object = (value: unknown) => row.safeParse(value).success ? value as Record<string, unknown> : undefined;

async function checked<T>(promise: PromiseLike<{ data: unknown; error: { message: string } | null }>, map: (value: Record<string, unknown>) => T): Promise<T[]> {
  const { data, error } = await promise; if (error) throw new Error(error.message); return rows.parse(data).map(map);
}

export const supabaseCensusRepository: CensusRepository = {
  async listCountries(): Promise<Country[]> { const db=await createClient(); return checked(db.from("countries").select("id,code,name").order("name"),r=>({id:String(r.id),code:String(r.code),name:String(r.name)})); },
  async listRegions(): Promise<Region[]> { const db=await createClient(); return checked(db.from("regions").select("id,country_id,name").order("name"),r=>({id:String(r.id),countryId:String(r.country_id),name:String(r.name)})); },
  async listProvinces(): Promise<Province[]> { const db=await createClient(); return checked(db.from("provinces").select("id,region_id,code,name").order("name"),r=>({id:String(r.id),regionId:String(r.region_id),code:text(r.code),name:String(r.name)})); },
  async listMunicipalities(): Promise<Municipality[]> { const db=await createClient(); return checked(db.from("municipalities").select("id,province_id,name").order("name"),r=>({id:String(r.id),provinceId:String(r.province_id),name:String(r.name)})); },
  async listOperators(): Promise<Operator[]> { const db=await createClient(); return checked(db.from("operators").select("id,display_name"),r=>({id:String(r.id),name:String(r.display_name)})); },
  async listStreets(): Promise<Street[]> { const db=await createClient(); return checked(db.from("streets").select("id,municipality_id,name,municipalities(name)").order("name"),r=>({id:String(r.id),municipalityId:String(r.municipality_id),name:String(r.name),municipality:String(object(r.municipalities)?.name??"")})); },
  async listCivics(): Promise<Civic[]> { const db=await createClient(); return checked(db.from("civics").select("id,street_id,number,extension"),r=>({id:String(r.id),streetId:String(r.street_id),number:String(r.number),extension:text(r.extension)})); },
  async listZones(): Promise<CensusZone[]> { const db=await createClient(); const [zoneRows,links]=await Promise.all([checked(db.from("census_zones").select("id,name,municipality_id,municipalities(name),operators(id,display_name)"),r=>r),checked(db.from("census_zone_streets").select("census_zone_id,street_id"),r=>r)]); return zoneRows.map(r=>{const op=object(r.operators);return {id:String(r.id),name:String(r.name),municipalityId:String(r.municipality_id),municipality:String(object(r.municipalities)?.name??""),operator:{id:String(op?.id??""),name:String(op?.display_name??"Non assegnato")},streetIds:links.filter(l=>l.census_zone_id===r.id).map(l=>String(l.street_id))}}); },
  async listComplexes(): Promise<Complex[]> { const db=await createClient(); const [complexRows,links]=await Promise.all([checked(db.from("complexes").select("id,name,census_zone_id,sheet,parcel,unit_count,description"),r=>r),checked(db.from("complex_civics").select("complex_id,civic_id"),r=>r)]); return complexRows.map(r=>({id:String(r.id),name:String(r.name),zoneId:String(r.census_zone_id),civicIds:links.filter(l=>l.complex_id===r.id).map(l=>String(l.civic_id)),sheet:text(r.sheet),parcel:text(r.parcel),units:typeof r.unit_count==="number"?r.unit_count:undefined,description:text(r.description)})); },
  async listRecords(): Promise<CensusRecord[]> { const db=await createClient(); const result=await checked(db.from("census_records").select("*,census_zones(name),streets(name),civics(number,extension),complexes(name),contact_types(label),operators(id,display_name),census_interviews(*,operators(display_name))"),r=>r); return result.map(r=>{const zone=object(r.census_zones),street=object(r.streets),civic=object(r.civics),complex=object(r.complexes),ct=object(r.contact_types),op=object(r.operators);const interviews=Array.isArray(r.census_interviews)?r.census_interviews.map(v=>row.parse(v)).map(i=>({id:String(i.id),recordId:String(i.census_record_id),operatorId:String(i.operator_id),operatorName:String(object(i.operators)?.display_name??""),interviewDate:String(i.interview_date),recallDate:text(i.recall_date),response:text(i.response),reason:text(i.reason),outcome:text(i.outcome)})):[];const contactType=contactTypes.find(v=>v===ct?.label)??"Generico";const floorCode=text(r.floor_code);const totalFloors=typeof r.total_floors==="number"?r.total_floors:undefined;const occupancy=occupancies.find(v=>v===r.occupancy);return {id:String(r.id),firstName:text(r.first_name),lastName:String(r.last_name),phone:text(r.phone),email:text(r.email),taxCode:text(r.tax_code),contactType,qualification:text(r.qualification),inherited:Boolean(r.inherited),birthDate:text(r.birth_date),responsibleOperatorId:text(r.responsible_operator_id),responsibleOperatorName:text(op?.display_name),notes:text(r.personal_notes),zoneId:String(r.census_zone_id),zoneName:String(zone?.name??""),streetId:String(r.street_id),streetName:String(street?.name??""),civicId:String(r.civic_id),civicNumber:String(civic?.number??""),civicExtension:text(civic?.extension),complexId:text(r.complex_id),complexName:text(complex?.name),buildingScope:r.building_scope==="Intero edificio"?"Intero edificio":"Parte di edificio",levels:typeof r.levels==="number"?r.levels:undefined,floorCode,totalFloors,isTopFloor:Boolean(r.is_top_floor),floorLabel:formatFloor(floorCode,totalFloors,Boolean(r.is_top_floor))??text(r.floor_label),rooms:typeof r.rooms==="number"?r.rooms:undefined,surface:typeof r.surface_sqm==="number"?r.surface_sqm:undefined,occupancy,elevator:typeof r.has_elevator==="boolean"?r.has_elevator:undefined,sheet:text(r.sheet),parcel:text(r.parcel),subaltern:text(r.subaltern),cadastralCategory:text(r.cadastral_category),isAppraised:Boolean(r.is_appraised),probableAssignment:typeof r.probable_assignment==="boolean"?r.probable_assignment:undefined,engagementType:text(r.engagement_type),createdAt:String(r.created_at),interviews}}); },
};
