"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import type { CadastralContext, CadastralHolder, CadastralOperationResult, CadastralPropertyUnit } from "@/domain/cadastral-data";
import { findPropertyUnitsAction, getCadastralDocumentUrlAction, getPropertyHoldersAction, importCadastralUnitAction, linkCadastralHolderAction, pollCadastralRequestAction, requestOrdinaryReportAction, requestPlanimetricElaborationAction, type CadastralActionResult } from "./actions";

type Props={recordId?:string;context?:CadastralContext;authorized:boolean;initialOperations?:CadastralOperationResult[];compact?:boolean};
const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
const holderName=(holder:CadastralHolder)=>holder.companyName??([holder.firstName,holder.lastName].filter(Boolean).join(" ")||"Intestatario non denominato");

export function CadastralServicesPanel({recordId,context,authorized,initialOperations=[],compact=false}:Props){
  const [operations,setOperations]=useState(initialOperations);const [busy,setBusy]=useState<string>();const [error,setError]=useState<string>();
  const latestUnits=useMemo(()=>operations.find(item=>item.operationType==="ELENCO_IMMOBILI"&&item.status==="COMPLETED")?.units??[],[operations]);
  const latestHolders=useMemo(()=>operations.find(item=>item.operationType==="PROSPETTO_CATASTALE"&&item.status==="COMPLETED")?.holders??[],[operations]);
  function store(operation:CadastralOperationResult){setOperations(current=>[operation,...current.filter(item=>item.requestId!==operation.requestId)])}
  async function execute(key:string,start:()=>Promise<CadastralActionResult>){setBusy(key);setError(undefined);let result=await start();if(!result.ok){setError(result.error);setBusy(undefined);return}store(result.data);for(let attempt=0;result.data.status==="IN_PROGRESS"&&attempt<20;attempt++){await wait(6000);result=await pollCadastralRequestAction(result.data.requestId);if(!result.ok){setError(result.error);break}store(result.data)}if(result.ok&&result.data.status==="IN_PROGRESS")setError("La richiesta è ancora in erogazione. Riprova tra qualche minuto.");setBusy(undefined)}
  function confirmCost(label:string){return window.confirm(`${label}\n\nQuesta operazione utilizza un servizio OpenAPI a consumo. Il costo effettivo dipende dal contratto OpenAPI. Confermi?`)}
  const find=()=>{if(confirmCost("Ottieni dati immobile"))void execute("units",()=>findPropertyUnitsAction({recordId,context}))};
  const refresh=()=>{if(confirmCost("Aggiorna dati catastali"))void execute("units",()=>findPropertyUnitsAction({recordId,context,refresh:true}))};
  const holders=(unit:CadastralPropertyUnit)=>{if(unit.id&&confirmCost("Ottieni intestatari"))void execute(`holders-${unit.id}`,()=>getPropertyHoldersAction({recordId,context,unitId:unit.id}))};
  const report=(unit:CadastralPropertyUnit)=>{if(unit.id&&confirmCost("Ottieni visura catastale ordinaria"))void execute(`report-${unit.id}`,()=>requestOrdinaryReportAction({recordId,context,unitId:unit.id}))};const plan=(unit:CadastralPropertyUnit)=>{if(unit.id&&confirmCost("Ottieni elaborato planimetrico dell’edificio"))void execute(`plan-${unit.id}`,()=>requestPlanimetricElaborationAction({recordId,context,unitId:unit.id}))};
  async function importUnit(unit:CadastralPropertyUnit){if(!recordId||!unit.id||!window.confirm("Importare i dati catastali dell’unità nel contatto? In Sandbox l’importazione resta bloccata."))return;setBusy(`import-${unit.id}`);const result=await importCadastralUnitAction({recordId,unitId:unit.id});if(!result.ok)setError(result.error);else setError("Dati catastali importati nel contatto.");setBusy(undefined)}
  async function openDocument(documentId:string){const result=await getCadastralDocumentUrlAction(documentId);if(result.ok)window.open(result.url,"_blank","noopener,noreferrer");else setError(result.error)}
  async function link(holder:CadastralHolder){if(!recordId||!holder.id||!holder.possibleSubjectId)return;setBusy(`link-${holder.id}`);const result=await linkCadastralHolderAction({recordId,holderId:holder.id,subjectId:holder.possibleSubjectId});if(!result.ok)setError(result.error);else setOperations(current=>current.map(operation=>({...operation,holders:operation.holders.map(item=>item.id===holder.id?{...item,linkedSubjectId:holder.possibleSubjectId}:item)})));setBusy(undefined)}
  return <div className={`paid-cadastral-services ${compact?"compact":""}`}><div className="paid-service-heading"><div><strong>Servizi aggiuntivi</strong><small>OpenAPI Catasto · operazioni esplicite a consumo</small></div>{latestUnits.length?<button type="button" className="button secondary" disabled={!authorized||Boolean(busy)} onClick={refresh}>Aggiorna dati</button>:<button type="button" className="button primary" disabled={!authorized||Boolean(busy)} onClick={find}>{busy==="units"?"Richiesta…":"Ottieni dati immobile"}</button>}</div>
    {!authorized&&<p className="muted">Autorizzazione ai servizi catastali a pagamento non abilitata per questo operatore.</p>}{error&&<div className="error-banner compact" role="alert">{error}</div>}
    {operations.find(item=>item.fromCache&&item.operationType==="ELENCO_IMMOBILI")&&<p className="cache-notice">Dati già acquisiti: nessuna nuova richiesta è stata addebitata.</p>}
    {latestUnits.length>0?<div className="cadastral-unit-list">{latestUnits.map(unit=><article key={unit.id??unit.providerPropertyId}><div><strong>Sub. {unit.subaltern??"non restituito"} · {unit.category??"categoria non restituita"}</strong><span>{unit.address??`Foglio ${unit.sheet}, particella ${unit.parcel}`}</span><small>{[unit.censusZone&&`Zona ${unit.censusZone}`,unit.class&&`Classe ${unit.class}`,unit.consistency,unit.cadastralIncome,unit.registryLot&&`Partita ${unit.registryLot}`].filter(Boolean).join(" · ")}</small></div><div className="button-row"><button type="button" className="button secondary" disabled={!authorized||Boolean(busy)||!unit.subaltern} onClick={()=>holders(unit)}>{busy===`holders-${unit.id}`?"Richiesta…":"Ottieni intestatari"}</button><button type="button" className="button secondary" disabled={!authorized||Boolean(busy)} onClick={()=>report(unit)}>{busy===`report-${unit.id}`?"Richiesta…":"Ottieni visura catastale"}</button><button type="button" className="button secondary" disabled={!authorized||Boolean(busy)} onClick={()=>plan(unit)}>{busy===`plan-${unit.id}`?"Richiesta…":"Ottieni elaborato planimetrico"}</button></div></article>)}</div>:operations.some(item=>item.operationType==="ELENCO_IMMOBILI"&&item.status==="COMPLETED")?<p className="muted">Nessuna unità immobiliare trovata.</p>:null}
    {latestUnits.length>0&&<div className="cadastral-unit-actions">{latestUnits.map(unit=><div key={`import-${unit.id}`}><strong>Unità selezionata {unit.subaltern??"—"}</strong>{unit.id&&<>{recordId?<button type="button" className="button primary" disabled={Boolean(busy)} onClick={()=>void importUnit(unit)}>Importa nel contatto</button>:<Link className="button primary" href={`/censimento/contatti/nuovo?cadastralUnitId=${unit.id}`}>Crea contatto da unità</Link>}</>}</div>)}</div>}
    {latestHolders.length>0&&<div className="cadastral-holder-list"><h3>Intestatari</h3>{latestHolders.map(holder=><article key={holder.id??holderName(holder)}><div><strong>{holderName(holder)}</strong><span>{holder.taxCode?`CF/P.IVA ${holder.taxCode}`:"Identificativo non restituito"}</span><small>{holder.rightTypeOriginal??"Diritto non restituito"}{holder.shareOriginal?` · Quota ${holder.shareOriginal}`:""}</small></div><div className="button-row">{holder.linkedSubjectId?<span className="success-inline">Associato</span>:<>{holder.possibleSubjectId&&<span className="cache-notice">Possibile soggetto già presente</span>}{recordId&&holder.possibleSubjectId&&<><Link className="button secondary" href={`/censimento/contatti/${recordId}`}>Apri</Link><button type="button" className="button primary" disabled={Boolean(busy)} onClick={()=>void link(holder)}>Associa</button></>}{holder.id&&<Link className="button secondary" href={`/censimento/contatti/nuovo?cadastralRightId=${holder.id}`}>Crea contatto</Link>}</>}</div></article>)}</div>}
    {latestHolders.length===0&&operations.some(item=>item.operationType==="PROSPETTO_CATASTALE"&&item.status==="COMPLETED")&&<p className="muted">Nessun intestatario trovato per l’unità selezionata.</p>}
    {operations.filter(item=>(item.operationType==="VISURA_ORDINARIA"||item.operationType==="ELABORATO_PLANIMETRICO")&&item.documentId).map(item=><button type="button" className="button secondary" key={item.requestId} onClick={()=>void openDocument(item.documentId!)}>{item.operationType==="VISURA_ORDINARIA"?"Apri visura catastale protetta":"Apri elaborato planimetrico protetto"}</button>)}
  </div>
}
