"use client";
import { useState } from "react";
import Link from "next/link";
import { euro, paidCadastralServicePrice, type PaidServiceGovernance } from "@/domain/paid-cadastral-services";
import { getCadastralDocumentUrlAction, updatePaidServiceLimitsAction } from "./actions";

export function PaidServiceGovernancePanel({governance}:{governance:PaidServiceGovernance}){
  const [message,setMessage]=useState<string>();const [busy,setBusy]=useState<string>();
  async function save(operatorId:string,form:HTMLFormElement){const values=new FormData(form);setBusy(operatorId);const result=await updatePaidServiceLimitsAction({operatorId,monthlyBudget:Number(values.get("monthlyBudget")),perRequestLimit:Number(values.get("perRequestLimit"))});setMessage(result.ok?"Limiti salvati.":result.error);setBusy(undefined)}
  async function openDocument(id:string){const result=await getCadastralDocumentUrlAction(id);if(result.ok)window.open(result.url,"_blank","noopener,noreferrer");else setMessage(result.error)}
  return <section className="panel paid-governance"><div className="panel-heading"><div><p className="eyebrow">Regia OpenAPI</p><h2>Costi, budget e documenti</h2></div>{governance.current&&<span>{euro(governance.current.monthSpend)} / {euro(governance.current.monthlyBudget)} questo mese</span>}</div><p className="muted">Importi configurati per richiesta: elenco unità {euro(.30)}, intestatari {euro(.30)}, visura {euro(1.90)}, elaborato {euro(6.90)}. Il controllo è applicato dal database prima della chiamata al provider.</p>{message&&<p className="cache-notice">{message}</p>}
    {governance.current?<div className="paid-budget-summary"><strong>Budget residuo: {euro(governance.current.monthRemaining)}</strong><span>Massimale per richiesta: {euro(governance.current.perRequestLimit)}</span></div>:<p className="muted">Nessun profilo operatore collegato alla sessione corrente.</p>}
    {governance.canManage&&<div className="table-scroll"><table><thead><tr><th>Operatore</th><th>Speso mese</th><th>Budget mensile</th><th>Massimale/richiesta</th><th/></tr></thead><tbody>{governance.operators.map(operator=><tr key={operator.operatorId}><td>{operator.name}</td><td>{euro(operator.monthSpend)} <small>residuo {euro(operator.monthRemaining)}</small></td><td><input form={`limits-${operator.operatorId}`} aria-label={`Budget mensile ${operator.name}`} name="monthlyBudget" type="number" min="0" step="0.01" defaultValue={operator.monthlyBudget}/></td><td><input form={`limits-${operator.operatorId}`} aria-label={`Massimale per richiesta ${operator.name}`} name="perRequestLimit" type="number" min="0" step="0.01" defaultValue={operator.perRequestLimit}/></td><td><form id={`limits-${operator.operatorId}`} onSubmit={event=>{event.preventDefault();void save(operator.operatorId,event.currentTarget)}}><button className="button secondary" disabled={busy===operator.operatorId}>Salva</button></form></td></tr>)}</tbody></table></div>}
    <h3>Storico richieste e documenti</h3><div className="table-scroll"><table><thead><tr><th>Data</th>{governance.canManage&&<th>Operatore</th>}<th>Operazione</th><th>Stato</th><th>Costo</th><th>Documento</th></tr></thead><tbody>{governance.history.length?governance.history.map(item=><tr key={item.id}><td>{new Date(item.requestedAt).toLocaleString("it-IT")}</td>{governance.canManage&&<td>{item.operatorName}</td>}<td>{paidCadastralServicePrice(item.operationType).label}</td><td>{item.status}</td><td>{euro(item.knownCost??item.estimatedCost)}</td><td>{item.documentId?<button type="button" className="text-button" onClick={()=>void openDocument(item.documentId!)}>Apri PDF</button>:item.recordId?<Link href={`/censimento/contatti/${item.recordId}`}>Apri contatto</Link>:"—"}</td></tr>):<tr><td colSpan={governance.canManage?6:5}>Nessuna richiesta registrata nel mese corrente.</td></tr>}</tbody></table></div>
  </section>
}
